#+startup: content

* 写给那些同我一样追寻真理的人

字数：217411字 访问原帖 评论数：24311条评论 TXT下载

发表时间：2015-12-12 06:52:00 更新时间：2021-04-22 17:01:25
* 1
** ...
楼主：星空迷航  时间：2015-12-11 22:52:00
躺在草坪上，背靠大地,睁开双眼，是一副神秘的、深邃的、无垠的、点缀着无数宝石的夜空。她的博大启示着生命的微小，生而何来，死而何去，犹如夜空中的流星，光耀一瞬。
为什么在太阳系中只有地球上有生命？有外星人吗？金星上是否有远古遗迹？月球真的是外星人的宇宙飞船吗？月球的背面真的有外星城市吗？地球上真的有远古文明吗？远古文明为什么会被毁灭，只余下团团迷雾般的，以现代科学也难以理解的遗迹。
我们这届文明，可追溯的历史也不过5000年左右，现代科学的形成也不过200年的时间。虽然还幼稚，但也发展到量子时代。科学愈发展，接触的难以理解的神秘现象愈多；我们需要一种新的科学理论来奠基，我们目前的科学界需要引导。
平常人度过童年，进入青年，然后结婚生子，养育孩子；孩子再成年，又结婚生子，养育孙子；然后，在等待中老死。千千万万的人如此，我不愿意过这样的一生，人海潮流多我一个不多、少我一个不少，我要做个异动者！
俗话说：不疯不成魔，不神经不颠。不务正业难成大业。我就是这样一个不务正业的人，但不觉大业何在。不过在追寻真理的路上，我已经走了很远。回首四顾，一片茫然；前看不见古人，后看不见来者。远望前方，荆轲泥泞，雾胧密矇中～彼岸～隐欲隐现，不知何时能否打开通往彼岸之路？
沉沦……
沉沦……
啊！
不要沉沦，
追寻真理的人！
……
在沉沦中奋起
……
其实我知道，彼岸就在我心中，在我们心中，在人的心中。要打开彼岸之路，需要积累多方面的力量，而不是仅仅凭臆想。因为我们不是阿Q、不是骆驼，我们是真正的人。
人心维维，圣心微微。维精唯一，渺兮寂兮。莲出污泥而不染，是自渡。对文明来说，自渡者孤。皮之不存，毛将焉附。我们需要的是～超脱～。
写到这里，心中不由浮现(硕鼠)中的两句：“……適彼乐土，莫我肯顾。”不知道，在这个物华横流的时代，还有没有需要指引的人？还有没有追寻真理的人？还有没有不断奋起的人？还有没有，不甘沦落的人？
有吗有乎？若有，你又能看见此帖，那么，我将在这里为你们作指引。把你们心中的凝虑、把你们心中的胆怯、把你们心中的不平、把你们心中的无明、把你们心中的毋妄，全部释放出来吧；在这里，我将为你们作净化、为你们作指引。
楼主：星空迷航  时间：2015-12-12 00:08:00
不知道怎么把帖子变到第一页去，愿有需要的人能看见
楼主：星空迷航  时间：2015-12-12 00:11:36
在这片星空中，你的一切凝问，都会在这里得到开示，得到答案
楼主：星空迷航  时间：2015-12-12 00:23:05
从今之后，每天的晚上23点，我会来天涯的这个贴，为大家解答，至1点结束。今天是12月11日，100天后，我不再作引导；若有需要者4年后再见。
楼主：星空迷航  时间：2015-12-12 01:08:51
转发
楼主：星空迷航  时间：2015-12-12 23:28:47
你有什么问题吗？
楼主：星空迷航  时间：2015-12-14 00:23:59
没人来吗，那就说一点东西。
长生之路：为什么树木可以活上几千年？为什么龟类可以活上千年？为什么蛇类也能活上几百年？可是作为万物之灵的人类，几十亿人中，活上百岁的都是稀罕难见？
原因啦是因为第四维的问题。爱因斯坦大人在他的相对论中给大家开了个玩笑。第四维不是时间，它是像一二三维一样，一个真实存在的维度。我们人类身体中就包含第四维度，但她却是全开放的，亿万人中有及其少量的人能，掌握她的部分。
第四维大大的消耗了我们的生命能，食物的补充远远供不上，所以，人们快速的进入了衰老期。故人类短寿。衰老就是一种病，一种能量病之一。
古代神话中的人物，他们亦不过掌握部分第四维的能量。
古代的宗教和修持者，就是为了开发第四维。
现今的人啊，没第四维及以上的理论支持，哪怕集全世界的力，也难以开发培养出超能战士，更不用说走出太阳系了。
能初步补充第四维的消耗，寿命就能达到千岁以上。古代传下来的相应修持方法～缺，也许在那些角落还存在着传承。
楼主：星空迷航  时间：2015-12-14 23:33:47
咦，居然来了一个客。
好吧，你的问题虽然有点飞，但我满足你。
本届10多年，在本届国家将会完成政治体制改革，到时有小战。
后十八子，又10余；在后女皇振兴。
好了，就这样了
楼主：星空迷航  时间：2015-12-18 00:47:28
验证真言三条件：
现在以神秘、恐怖、灾难、末日、救赎等新理论新神棍，诱导众人思维的伪引导太
多，在追寻真理路上要明辨：
第一条、你相信她她存在，你不相信她她仍然存在；
第二条、你给条件她她存在，你不给条件她她依然存在；
第三条、谬论在某种局部范围或某种条件下，可能转化成相对真理。
楼主：星空迷航  时间：2015-12-19 01:01:39
今天没人来了。第一次到天涯来引导，无人需要。那我就守侯到2015年底吧。看有没有一个敢于尝试的人。
楼主：星空迷航  时间：2015-12-20 00:55:23
心之一念是缘启，愿心了达是缘灭。
右六六，左三三，水和酒，比清甜。相思红尘外，漫步彩云间，问世间，什么是缘，只在人心间。
楼主：星空迷航  时间：2015-12-22 23:48:43
回复：恒古常新
真理是我们这个宇宙中恒古不变的规律。但宇宙规律，我们地球人类了解有限，思维方式理解能力有限，能明白的不多。比如，万有引力定律，我们目前认为她是真理。但是，更进一步，引力波是什么东西，引力波怎样把引力传送的，我们的万有引力定律就弄不明白了。认识真理，理解真理，运用真理，掌握真理，掌握真理背后的真理也就是了解我们这个宇宙的真相，这需要一个过程，不断有人无悔努力的过程。
目前，我们的科学界发展到量子阶段，很多方面的科学研究都遇到了挑战，难以有进步；原因就在于，我们的现代科学发展太快，积累不足，基础科学的认知还不够全面；对自然界的许多现象，都只能冠以超自然现象、神秘未知等，难以解释。所以许多现代科学家都转而研究宗教哲学，是因为发现了它们之间的某些共通之处。这就需要打破传统，诞生新的基础科学理论；需要看破现象，直指宇宙本来的理论。我举个例，人们为什么会做梦？这个世界中有没有鬼神？为什么到处都有人们信仰的庙宇？到底有没有风水？修建高楼大厦的没有不讲究风水的？……这些，其实都说的一样，一回事，有一个共同的东西把它们串通！～认识了，就没什么神秘了；不认识，就是迷信，就是超自然现象。要认知它们，需要一种新的科学理论。没有科学不能解释的，只是目前我们的科学基础理论不够。
楼主：星空迷航  时间：2015-12-23 23:07:05
今天又清净一日
楼主：星空迷航  时间：2015-12-24 22:08:01
今晚停电了，无线网络很慢……
楼主：星空迷航  时间：2015-12-26 00:34:01
又是一天过去了，元旦的钟声也不远了。就让我把“观粟老道”的那个伟大问题作为了结吧。我会分层次的引导，愿大家有更好的选择。其实，生命即伟大又渺小，更多的却是无赖！
楼主：星空迷航  时间：2015-12-26 23:05:48
人活着的目标是什么？
一个非常大的题目。我在这里试着为大家解言。不过在解言前，我们先看看它们怎么活着的。
楼主：星空迷航  时间：2015-12-26 23:47:56
蚂蚁遇上水火怎么办？
去年2014我在中央台(人与自然)节目看到这么一件事。一群黄红蚂蚁巢穴在一个小山包上，雨季到来，小山包成了孤岛。所有的蚂蚁都出来了，有的托着蚁后蚁王，有的托着蚁蛋，其他都围着水边，成一圈黄红的坝不停的骚动。不久，不知道什么原因，蚁坝出现了一个缺口，蚂蚁们不停的通过缺口涌向水中；镜头下，它们互相咬着肢体，拼命张开着肢体，在水面铺成了一条桥坝，前仆后继，从孤岛不断延伸向对面的山头。经过一段时间后，蚁桥得以打通，剩下不到一半的蚁群，托着蚁后蚁王蚁蛋，逃到了更高的山头。整个蚁群安全逃脱大难。
在这里，那些死了的蚂蚁为了什么？是什么原因让它们有组织的面对死亡？我们的科学认知，蚂蚁是没有智慧的，但是在族群生死存危时，它们却展现出了超人般的智慧！
在自然界中，像这样无智慧的个体，展现出超人般智慧的示例有很多，某些人甚至把它们作为神存在的证据，加以狂吹；在这里我们不必讨论，但是，我要问下有智慧的人，死前的蚂蚁在死前为了什么而活着？逃出生天的蚂蚁，它们今后又为什么而活着？
楼主：星空迷航  时间：2015-12-27 00:24:50
现在，我们可以回头看看，作为智慧生物的人类了。
在儿童时代，蒙昧无知、天真无邪，他们活着就是为了成长。
在少年时代，在不断学习中，智力渐长，自我意识得以展现，六七十年代时，他们活着就是为了解放全人类，实现共产主义；八九十年代，好像是实现四个现代化，2000年奔小康；千年之后，人们的心已很少淳朴了，在学校、家庭、社会的成长中，他们很多的选择是，读个好学校、找个好工作、然后发大财再完成其它想法。
在青年时代，从家庭进入了社会，现实同梦想对撞，从白布染成彩色，百味人生就此诞生。
我试着为大家展现。
楼主：星空迷航  时间：2015-12-27 00:40:06
几天前，好像是22日吧，一湖南青年，从峨嵋金顶舍身崖上，一跳而下。新闻说，他家庭复杂，由大伯养大。那么他生前怎么活着？为什么而活着？而今一去之后，留下关心他的家人们，又该怎么活着为什么活着？
楼主：星空迷航  时间：2015-12-27 01:06:33
你看看那些明星们，昨天拍拖，今天又换了个朋友，明天找到个富豪，后天又同另一个明星生活在了一起。他她们又为了什么而活着？
你看看那些抢劫犯、那些杀人的(好像前几天新闻中，就有个保姆杀了10位顾主)，他们又为了什么活着？难道他们活着的目标就是抢劫、杀人吗？
你看看那些被打的老虎，那些腐败分子，为了金钱想尽了办法。有卖官的、有裸官移民的、有藏现金的、有藏玉器的………他们又为了什么活着？难道仅仅是为了享乐吗？
你看看那些，无偿捐献器官的朋友们；你看看那些，为了亲人无偿付出的人们；你看看那些，在地震等自然灾害时，战斗在第一线的人们；你看看那些，比如在前几天深圳滑坡是时，得到救生的人们……………他她们为了什么而活着？

* 2
** ...

楼主：星空迷航  时间：2015-12-27 01:21:21
一言不可尽量。生活中有为金钱而活着的、有为爱而活着的、有为情而活着的、有为仇恨而活着的、有为工作而活着的、有为权势而活着的……万人有万心啊，万心有万缘，万缘结万因，万因生万果。
这就是人生啊，无论贫贱高贵，只要你活着，就得为活而度日。无论正气的活着，还是卑贱活着，生活都是一份无赖！
我们都因为活着，那么活着的真相有吗？又为了什么？
明天接着继续解言。晚安
楼主：星空迷航  时间：2015-12-27 23:27:11
今天继续～活着的真相？
要知道活着，那就离不开我。活着的是生命，我是谁？
我识我在故为我。过去、现在、未来，我代表现在。以道家看来，我就是识神，是这具肉身来到世间后天培养形成的智慧。所以，我不是身体基因中隠藏的潜意识，而是身体后天成长形成的智慧体，是身体现在的执政者。
因为我存在，所以我活着。我不存在了，但肉体仍可能活着，所以世上医院里有了～植物人！但是，植物人不等于我不存在了。
所以，活着的前提必须要有我。没有了我，活着的它是谁？
所以，我也是肉体这一世经历养成的灵性。我的成长需要父母、环境、社会的熔炼。
楼主：星空迷航  时间：2015-12-27 23:53:19
婴儿时代的我，白玉无瑕，灵性淳朴。打个比喻，无属性。
儿童时代的我，接受外界培养，灵性被引导成长，始染。打个比喻，开始出现属性了。
少年时代的我，外界对我的引导减弱，进入自我成长阶段，我的对外免疫力增强。属性增长。
进入社会的我，就像上了战场的新兵。社会是个大染缸，战场是个大熔炉。有可能我属性继续增长，有可能我属性下降，有可能我染成了多属性。
楼主：星空迷航  时间：2015-12-28 00:30:46
生命既伟大又渺小，生命既无赖又来之不易。既然世上有了我，我就应该勇敢的面对一切。
牧羊人对羊羔说，你们要信我的、听我的，我会给你们吃不完的嫩草、喝不完的甜水；不新我的、不听我的，你们有大罪，我将降下惩罚，让你们时时饥荒、日日干渴。
农夫站在麦田边，对着杂草说：你们的末日快要到了，我将降下毁灭之焱，把你们横烧；只有那饱满的麦粒，将被我收割入仓，可以躲过灾难。不久，麦子熟了，农夫兑现了他的诺言。
世上没有无缘无故的爱，宇宙的真理之一“交换是等价的，能量是守恒的”。付出了，不一定有收获；但没有付出，就绝对不会有收获。
求人不如求己。哪怕面对荆轲泥泞，我也要斩出一条路来。
楼主：星空迷航  时间：2015-12-28 00:35:42
因为我在，所以我活，我要生活。但我怎么生活，进一步的真相有吗？明日再议。
楼主：星空迷航  时间：2015-12-28 23:11:38
报道来了。今天继续一点点揭示我活着的真相。
楼主：星空迷航  时间：2015-12-28 23:38:28
我们这届文明啊，非常不易。之前的，仅仅在时光中给我们留下一些远古的痕迹，像英国的巨石圈、埃及的金字塔、复活节岛的巨石人头像、秘鲁的巨型刻画、中国的河图洛书等等，给后人瞻仰那慌远的文明气息。
在我们这届文明中，多种传承并存，也得到了遗留的引导，十分不易啊。
当然，不能熔合、不能理解、不能升华形成文明自己的体系，也难免逃脱毁灭的命运。
看到这里的朋友们，心中凝惑了，你凭什么说文明被毁灭啦？虽然时候不到，但能看见这个帖子的人是需要缘分的，所以我就展示一点点。
真相就是，我们生存的地球，我们文明诞生的母亲，她是一颗生命星球。
在星河系，愈往星河中心，生命存在的可能性就成指数般的增长。但是，任何一颗生命星球都是极其宝贵的。
因为，生命星球有可能诞生生命意志。确使整个星球保持最佳的状态。这就是天意！
楼主：星空迷航  时间：2015-12-29 00:04:51
我们这届文明是最有可能超脱的一届。大环境的引导就此。
我们生活世上，住食行思，都需要消耗能量，身体时时同外界发生能量交换。物质，可以看成是凝固了的能量。以供我们成长。
在这些交换中，效率是很低的。但有些资源，我们的身体能够得到更好的利用。比如，药物治病就是。
成长离不开资源。目前我们这届文明还处于被动进化时段，应该转入主动进化时代了。
在太阳系中，所有的资源，可以分为两类。生存资源和进化资源。所谓生存资源，指的是为文明生存延续所必需的资源，它具有一个特点，就是可以再生。目前我们地球上发生的种种战争，都是为了抢夺生存资源。
进化资源，是每界文明最宝贵的资源。进化资源它的再生需要万年以上，甚至某些还需要在特殊的条件下才能形成。进化资源，是促进文明耀迁的。任何一届文明，只要浪费了进化资源而又没能实现文明耀迁的，必然会走向毁灭，必然逃不脱毁灭。
所以，我们需要的是超脱。
目前我们太阳系可以列为进化资源的，可能有六类。因为某些还在形成中，今后形成还需要人类的努力。
楼主：星空迷航  时间：2015-12-29 00:24:48
其中，最基本的进化资源，是生物量子场。全地球生命界生存的基础。
基础知识的引导就到这里，过了，没人珍惜。
我活着的目标是什么？我想超脱。有了资源，还需要懂道理，懂了道理，还需要贯彻的方法。掌握了方法，还需要你时时执行，与之相应。才有可能产生效果。
现在我们文明，如不能转型，那就将走入末世。心灵难以纯洁，大气中充斥着怨力。末世要超脱需修行，不是修持。末世修行，最重要的是修心。这里面有什么秘密，下次再说。
楼主：星空迷航  时间：2015-12-29 23:54:47
报道了。
我记得在当年气功大师满大街时，为求大法、为修特异功能、超能力，有从新疆、内蒙、湖北、浙江等等来自全国各地的朋友，许多人甚至从企事业离职、放自家公司不顾、弃家追随大师们，以求法。好艰难好坚硬。
那时某日许多人希望我指引，可惜当年的我是抱着考察研究并亲身实践修行，尽管比大多数人都体会深、看得远一点，但我以度人先度己，自己还在迷雾中摸索，同大家交流了一番。当年一别，我记得还有很多朋友劝我们一起江浙去求法。
如今，我以透过迷雾看见那真相大道，你们还在吗？还在追寻吗？
如果你们看见此帖，请细查我留下的引导信息。
我记得当年从藏区回归时，过鹧鸪山口，看见成都方向新起了一片金红色的雾气，充满了铜锈的味。此最能迷失心灵！
楼主：星空迷航  时间：2015-12-30 00:32:40
大法难求，大道难寻。其实直通大道的大法，就在我们身边，只是人不识。
诵经。我说其实诵经是直指大道的大方便法门。请观唐及以前的修行。
一般早晚诵一次，或者自己方便时诵读都可以。随时随地，坐卧皆可。若能做到经文从口出，从心中流过，同身相应，那是一个好。
诵经是大方便法门，直通大道。所以修行中，会出现能力，都是付产物，要有取舍。佛家说，慧而不用。
选择的经书，喜欢佛家的有观世音菩萨心经，地藏菩萨本愿经，金刚经等。喜欢道家的有道德经，黄庭经，黄帝阴符经等。其他经典也是可以的。
时间充足可以多诵读几篇，诵读一次也可。关键是要澄心。
推荐观世音菩萨心经、黄帝阴符经。初期最易，洗涤心灵。熟悉了可诵读地藏菩萨本愿经，这个要的时间长。
为什么，诵上一万扁你就知道了。
楼主：星空迷航  时间：2015-12-30 00:47:47
人们活着，心中有种种不甘，念头一起即需了达，方可斩灭。愿满，心洁，自定。
楼主：星空迷航  时间：2015-12-30 23:12:44
又是一天
楼主：星空迷航  时间：2015-12-30 23:34:00
本想引导100天，赖何人心已冷漠，很快就31最后一天了。
虽然很多方面我开头就藏尾，但能看见的坚持的都是缘，希望你们能多的转发，让更多的需要的人得以看见。可以引领可以深思。
在我们这个宇宙中，或者说地球上，科学、宗教最终会易途同归，西方的占星、东方的风水命相易经它们也是一个道理，不过迷雾下的幻变。
追寻真理是不容易的，打破迷雾是有代价的。所以，我愿大家别细问，打破迷雾后才知道，原来圣贤留真言，直通大道在身边。选择一本你喜欢的经书，试尝去修行，这是最合目前这世道人心的大方便法门。
楼主：星空迷航  时间：2015-12-30 23:41:28
过了今天，我也要在红尘中继续洗炼，恢复我那震撼而受损的心灵。
临别通报一个预测，希望有个好的选择。
楼主：星空迷航  时间：2015-12-30 23:59:02
孔明八字碑：空、争、名、利，难、逃、杀、劫。就发个一半吧。
空空空，四面粮食要集中，饿死贫穷汉，气死富家翁；
………
逃逃逃，大人定要出剑袍，斩尽众魔军，三教定功劳；
杀杀杀，五洋五国闹中华，万邦来送命，日月定绑家；
劫劫劫，飞机炸弹一现灭，快枪成废物，都州发佛国。
这是81年大水时，四川一座大山塌了半边，出了这碑，后被封。有长辈去看了记下来，虽然有很多不通之处，但先贤留下的精义不能不传。
楼主：星空迷航  时间：2015-12-31 00:03:03
你们的心都冷漠了吗？我悄悄的来了，我即将悄悄的走了，没人能识。
楼主：星空迷航  时间：2015-12-31 23:14:38
呵呵
楼主：星空迷航  时间：2016-01-11 02:29:17
本来过了2015年，我是不准备在说些什么的，原来还没30天，的确我是11那天发的。藕断还丝连，天意余机!
楼主：星空迷航  时间：2016-01-11 02:40:46
文明劫难是免不了的。文明要超越，就涉及对资源的消耗，就会对星球环境带来破坏。无论是对星球本身意志或者外来的，都会产生影响，所以，海洋动荡、气候反常，甚至地裂地震等频发，这是警示。多种原因集合，我们这届文明的劫难也就不远了
   
* 3
** ...

楼主：星空迷航  时间：2016-01-11 02:55:18
在2014年时，我随在各地，空气中大地万物上的慌气基本达到三层到半层，2015年8月后，这种气息最多的地方不足半层，大有改善，原因不明。但天机隐若，地球如暴风雨前的宁静。外力支援，大劫依然。回看先贤留下的警示，天有定数，但人力在小小范围已经有了改变。出力的很多，修者自明。
楼主：星空迷航  时间：2016-01-11 03:06:22
末劫之难，有人祸，有天灾，有地变。人祸三战起点在中东，但看土耳其与俄罗斯；我国有争权，独立冰霜涣，五贼来夺利，日月定新天。
楼主：星空迷航  时间：2016-01-11 03:13:48
推B图，是先贤留下的指路明灯，心灵的力量，按照天演规律，可以观之。我看见的版本，很多都顺序变换，少量文字变换。
楼主：星空迷航  时间：2016-01-11 03:32:32
现在在一二叁(三)四这相像，即将进入木火金水洗此大辱。
楼主：星空迷航  时间：2016-01-11 03:37:50
木子作将，今已现。木火受辱，金水洗。呵呵，明白不。这是我的看法。
楼主：星空迷航  时间：2016-01-11 03:49:46
还修行，在我们文明，以修心灵为最高。修心灵，可以快速打开高维，得以超凡脱难。修武修脉修無，可以开发第四维，渡难。
2016年了，但是国历，易简如上。
修心最方便的大法门，就是诵真经。还有情无情众生，皆易入门，见效速。
楼主：星空迷航  时间：2016-01-11 03:58:50
申酉兵刀起，16～17，也可以28～29。35年后见太平，这是初劫了结。我这就不讨论了，或许……
楼主：星空迷航  时间：2016-01-11 04:22:23
诵真经。心印七宝，一。
初学者，可以先听，熟悉经文节奏后，可口相应，再身相应。
心经，阴符经，大悲陀罗尼，慧命经，道德经，地藏菩萨本愿经，金刚经，黄庭经……。
楼主：星空迷航  时间：2016-01-13 10:33:08
本来不该回帖的了。但即余机，问我，可以的做达。我不能像别的指导人那样，我只是引导，需要您们用心去分析，我只是开线头
楼主：星空迷航  时间：2016-01-13 11:36:06
那里回复受字数限制……。
远古众灵来到了地球，他们很喜欢这里，决定找个代理来打理。第一批，他们造出了扫把人，但是扫把人很残暴，他们力大无穷，以众生为食，把地球弄得乌烟瘴气，所以被灭了。
第二批，众灵造出了千担人(巨人)，千担人非常聪明，把地球打理得整整有条。最后，千担人们想自己做主，他们同众灵开战，打得天翻地覆，他们攻入了众灵的居第(分析，我怀凝是月球)，但最后战败，残余从北退入地心(以此，我认为地球是空心的，北极该有进入的门户)。
第三批，众灵用自己基因同远古地球生命基因一起，造出了扁担人，就是我们这届文明。
楼主：星空迷航  时间：2016-01-13 11:39:15
众灵希望我们能进化成为像他们一样。所以我们这届文明的使命就是进化。
楼主：星空迷航  时间：2016-01-13 12:49:30
这里面真相很复杂，但这个造人传承是真的。没有什么既定的命运，预言也不是神秘的。举个例子，了解地球围着太阳转的规律，现在是冬天，我预言3个月后将进入春天，6个月后进入夏天，呵呵，预言就是这样。
楼主：星空迷航  时间：2016-01-13 13:01:46
所以，很多人担心啊，既然命运已经编排好了，人们活着还有什么意义。人们活着，与桃树春天开花，荷花秋天叶枯，这种规律又有什么区别呢。但是，每颗树都不一样的，每朵花都不同的，所以生命的意义之一就是要奋进，依时造运，活出自己的特色。逆流只能勇进，等待的，就像那牧羊人许愿的羊羔，命运可以预测，但命运又是多变的，人心啊。
所以末劫时期，当修心。
楼主：星空迷航  时间：2016-01-13 23:30:16
回格录：您意我已知道。
我发帖是遵照天机规则，对所有我的引导负责，所有内容都不会带自己强加意念，尽量符合规则。发帖时受了几年劫难，刚满，回想起以前的应言，故有此帖。直到您和都都…的留言，我才明白，我忘了自己的使命所以有劫难，差点啊。自己专了牛角，难悟。所以，别人泄露天机受劫，而我恰巧相反。
我们身在红尘，最次的都可以算是一个被动修念者。所以骂人会使人感到不舒服，骂人的话就相当于低级的言咒，强加自己意念的话语，就相当于心灵锁，给认可的人加上，被动的加上。因为带这种语言的人们可能自己也不明白，所以，处于领导职位的人对他她的下属有威严，这也算被动修念了。
所以，我做引导，给大家解线头，不带自己的意念(特殊情况需要加以说明的例外)，不能宣扬自己，一点都不能。因为我引导大家，不需要任何回报感谢，是完成任务。有一人接受我也算成功，不过，我还是愿有更多的有缘人。
借此，我真心的感谢前进路上引导我的大德们和守护的。
90年前后我接触领导都能为民作想，后来的处处都是TG，很是失望啊，所以打算自渡。忘了哦，受了几年劫难。
我愿后来留言的朋友们，不要把自己的主观意识带入帖子！谢谢。
再次，无论您有多大的业，看见此帖，请您放下心灵的执着，在帖中仔细寻找指引的方法，速速实行，逃脱末劫大难。
末劫，很近很近了啊。
楼主：星空迷航  时间：2016-01-14 13:47:24
大劫前我都会在这儿引导有缘人，做心灵方面的开示。我愿管理此帖看见此言的，在帖子题目前加上“心灵鸡汤”几字。
楼主：星空迷航  时间：2016-01-14 23:53:51
今天没提问了。看了些推b，里面解的很乱，按错的错解，呵呵，，无聊。
我试着跨区，为喜欢这方面的试解一像，就此一像。
楼主：星空迷航  时间：2016-01-15 00:00:13
推b,是传为唐人李淳风作，故解需用唐人时的物像及言论。此帖不作这方面讨论，我试解一像，为爱好的来此帖的人们作思路之引。故预言，可研究，但不要迷信，没什么神秘。
楼主：星空迷航  时间：2016-01-15 00:19:13
找了半天，就目前争论最大的45？
畿曰：有客西来，至东乃止。木火金水，洗此大辱。
诵曰：焱运宏开世界同，金乌隐藏白洋中，从此不敢称雄主，兵气全消运已终。
有客西来～李淳风在唐是观天监的，所以史上有观天记录“客范主”，何言？客者指客星，主者指主星紫微星。故“有客西来”之客，当作星解。白话说，就是“有客星从西边而来，向东方而去”。客星，古指彗星，勃星。
楼主：星空迷航  时间：2016-01-15 00:34:27
至东乃止～东者，当作日出之地解。唐时搡枝国使者自称为，代表日出之地的国君前来拜访日落之地的君王，就是这意思。
止者，停止，归也，终也。
两句连起来说，当天上有客星从西边飞来的时候，日出之地该终了。
楼主：星空迷航  时间：2016-01-15 00:41:53
木火金水～此是表示时间，古人以干支记年。木火，就是木火年收；金水，就是金水年。
洗此大辱～洗去受到的大辱。大辱，当是木火年受的。金克木，水克火，故金水年反转，可以洗去。这里显示着一种客观规律。
   
* 4
** ...

楼主：星空迷航  时间：2016-01-15 00:54:03
木火者，甲午也。金水者，庚子也。
焱运宏开世界同～古人以运计时比较大一些的年份，按三元甲子，一运是20年。焱运，代表的是下元甲子的离卦九紫星。我们现在就处于焱运，2004年开始。
世界同，是指世界一体化。此句意思是，进入焱运时，世界上当出现新气象，走向一体化。
楼主：星空迷航  时间：2016-01-15 01:05:24
解到此，看者已明。有请众灵谅解，我借此点醒那些来的、傲气充心的、迷恋预言的有缘人，愿他她们放下，从此帖中明悟出而修心，提升心灵，以渡末劫。
嗡，嘛，哩，呗，咪，哄！
楼主：星空迷航  时间：2016-01-17 21:38:58
情义如众，借此帖，小七只能真诚的祝福您：三哥一路好走！
15日临晨，无意识的把大明六字祝託出来，有燥意来，上午九点多得知因脑溢血三哥走了，世事无常意惆怅。
三哥，北方的鄂伦春人，性格豪爽,爱助人，个子瘦高，喜喝酒，身体很结实。大学后入国企，留有一女，工作。
当年一别近30年，想到元旦时您还短信来问候，转眼已是两重天。小七在少年的命运选择时，“财富”和“智慧”我选择了后者，所以与众同学们走了一条不同的路，我没法满足同学们的要求，敬请三哥在他界谅解！我小七祝福您在他界好好修行，实现自己的愿望！小七祝福晶晶一生幸福快乐平安！
楼主：星空迷航  时间：2016-01-17 21:47:46
借用了此帖，为回报看帖的朋友，我会在明日将大明六字的用法贴出。
春节前我会将修心的真源解禁。

～～～～～～～

虽然，逼我做了选择，
但是，也是成全了我。
楼主：星空迷航  时间：2016-01-18 22:31:15
今天提前点，开始打字……
楼主：星空迷航  时间：2016-01-18 22:43:47
真言！
是修行人通达彼岸时，回头观世感悟的大道之音。无论佛道儒，高层次都是诵真言。只是众大觉不明言，而身教。留下真言法门，觉是各门的入门修持，无量不出应难悟，今至末劫，故传之。观之者切轻视之！！！
楼主：星空迷航  时间：2016-01-18 23:09:22
六字大明真言：嗡(weng)、嘛(ma)、哩(li)、唄(be)、咪(mi)、哄(hong)。皆是一声。其中有些译本，因要合梵文，用字不一，以音为上。
六字真言又为大明咒。属于佛教密宗莲花部，缘起于莲花生大士祈往极乐世界所唱的六字。
密宗六字真言的原修行次第，要求身、口、意三密我就不说了，因为在末世，那样修行对大家有影响。因有范例，可以先听，掌握音之节奏了，同时诵，最后随地诵。寻找范例时，应上师的较好或者试听时对身体共振感最强的。
楼主：星空迷航  时间：2016-01-18 23:23:55
密宗，藏密。真言多是可以辅助修炼气脉明点，开启脉轮，提高能量等级。最主要的是开通中脉，她就是人体的南北两极，约束身体的生命量子场。
六字真言，是可以打开人体中脉的，六字从上到下与人体相应。
诵经，是相应法门，所以不能在这里细说。不同人会有不同的体悟。末世诵经一样可以达到苦修的效果。相应者，取“易简则易行”之义。
楼主：星空迷航  时间：2016-01-18 23:42:05
六字真言，可以祛除身体的不适。无论有咒言、怨力、业力(那个业不好打)临身，就会在胸部感到不适，影响气脉，位置相当于人体的颤中穴，最后通过颤中部位，传之。
故有时，人会无缘无故的感到，心胸烦躁，即有不好的能量或信息在影响您了。
此时，加持六字真言，听诵皆可，多相应。以真言能量疏通不适部位，很快得以恢复。
用于调理身体，同此理。
六字真言，能洗去尘气，使清凉气息在心灵中扩展。
楼主：星空迷航  时间：2016-01-18 23:49:23
其他真言，也可如此修行。道家真言范例难以见，诵道家真言，以像相应。
相应，两方相互感应。用现代科学说法，就是能量共振状态。
楼主：星空迷航  时间：2016-01-20 02:46:21
今天，有很多人问了。
心印七宝，无量诀。修行人，常称无量，那什么是无量呢？
看见鸟自由飞翔，我想要一双翅膀；看见鱼自在游，我想要水中不息；看见花开花落，我想要青春常在………这些念头，就是超脱之念。
积累到某时，您真心感动，从内心深处发出一个超脱的心念，这就是无量。
无量心生破万法。无量心生，光耀四方，此念，轮回不可挡，神魔不能灭。
楼主：星空迷航  时间：2016-01-20 23:17:59
今天是大寒节，还得冷几天。
楼主：星空迷航  时间：2016-01-20 23:21:26
这里是一个小小的引导，请不必与高大上齐观。
楼主：星空迷航  时间：2016-01-21 20:52:12
内心的第一想法，就是最好的选择。把真灵，视同为一个容器，那么生灵在轮回中每世的精华(能完善或符合自然规律)，会自动的被存入。这可以试看为轮回进化，或许主动或许被动。
所以，可以把真灵看为本我的储备库，即是我又不等同于我。本我修行，能使真灵高速成长。本我修行至纯净无瑕，就能同真灵合一，获得无所定处定，在佛教就是肉身金刚不败。
楼主：星空迷航  时间：2016-01-21 21:11:44
道家九字真言：临兵斗者皆阵列前行。初出于东晋葛洪的“抱朴子内篇”，为道家六甲秘祝。佛教密宗，也有此九字真言，与观想法(如白骨观)结合，修念的大法之一。佛教东渡，传至日本，成为真言密教法门，并将九字误抄为“临兵斗者皆阵列在前”，称之为东密。
楼主：星空迷航  时间：2016-01-21 21:13:27
其实，九字真言，是远古传下来的法门。佛道都得以继承。
楼主：星空迷航  时间：2016-01-22 23:19:59
人的真念有大能。所有外源信息，都是通过引导您，您信才能干涉影响您。
楼主：星空迷航  时间：2016-01-22 23:30:08
今天更新一点，基本时空观。
时空，我们天天经历，但却看不见摸不着。至爱因斯坦时空观之后，现代科学目前还没新的系统时空观。
楼主：星空迷航  时间：2016-01-22 23:42:35
现代科学，有认为，空间有11维。
一维是线，从线上任取一点，任意方向延伸形成第二条线，两线相交组成面。二维是面，面上引出一垂直线，构成体。三维是体。从线到体，正解都是垂直关系。
三维构成物质界度量。那么，能不能找到垂直于三维的第四维呢？很多人都没找到，所以爱因斯坦将时间，引入为第四维。
楼主：星空迷航  时间：2016-01-23 00:07:15
先有空间，后有时间。相对时间，可以表述为空间位置的度量。时间是不可逆的，但是，在很小的局部，付出巨大的能量，可以回逆。
第四维是真实存在的。前面三维都可以用线来表达，人们就专了牛角，所以找不到从数理上垂直于三维的线。第四维，是用膜表达，它是垂直于前面三维的一个球面。现实生活中，存在的各类场(引力场、磁场、电场……)，就是通过第四维度表达的。
   
* 5
** ...

楼主：星空迷航  时间：2016-01-23 23:07:26
看帖的朋友们，选一本自己喜欢的经书，修行吧。修行下去就有超脱的那天。
楼主：星空迷航  时间：2016-01-24 23:10:07
报道了。这个帖子的许多信息，都需要大家身躬力行，就会有新的体悟。
楼主：星空迷航  时间：2016-01-24 23:15:03
我们这届人体，存在第五维，修心就是开发第五维的。
三维代表物质体，四维代表能力，五维代表掌控。珍惜吧，有缘人。
楼主：星空迷航  时间：2016-01-25 23:56:11
人们常说：相随心转。心灵修持，气质合道。
楼主：星空迷航  时间：2016-01-26 23:37:34
我从大家的言语中一些消极无赖的。其实这是外在的不良信息，在影响您了，修心吧。
现在的网络小说超多，我也看的，某些比较灵性的，还是能给人们启发的。但大多的，都是含有不少的心灵枷锁，您认同了，就在心灵上蒙上迷雾了。比如，分什么1～9级，突破什么膜……。
实践心灵修行吧，洗去心灵上的迷雾，消除心灵上的枷锁。用灵性的观小说，自明自悟。
楼主：星空迷航  时间：2016-01-26 23:48:27
修行是为了超脱。怎么修？就是通过，一定的方式方法，体悟道之理，相应，打开人体内部与高维的通道，蜕变。
说得过多，对初学者会有干扰。所以，心灵修行，在蜕变自己的同时，也在不断开悟，后面的路会自然明白。
楼主：星空迷航  时间：2016-01-27 00:00:56
不要被预言中的种种，劫难蒙蔽 。不要被人们常识中的种种，传说蒙蔽。不要被迷雾中的人们的种种，猜测蒙蔽。宇宙的真相，不是那样的。
追求金钱的，易被铜臭气蒙蔽；追求女色的，易被六欲蒙蔽；追求法力的，易被能力蒙蔽。………
为修行心灵的，能洗去迷雾。
楼主：星空迷航  时间：2016-01-27 00:20:51
无论您如何，为什么不能试着进行，心灵修行呢？为什么不行动呢？为什么不试一试呢？
心灵修行，能开启灵性，在心的部位会清凉气息，洗涤身体中的浑浊，开悟。
在您迷惘时，在您无聊时，在您消极时，按心灵修行引导，听听经应该不难的。
楼主：星空迷航  时间：2016-01-27 23:07:47
腊月十八了…明天说说梦修。
楼主：星空迷航  时间：2016-01-28 23:06:33
修心，就是要心灵纯洁意志恒定，不为外染。平常人们，为了生存，心神外耗，杂念丛生，所以修行难入门。故有修行先练己，锁心猿栓意马，神意相合。导引服气、经脉搬运、武术中的桩、书法绘画……初期都是这目的。诵真经也是此。净意，一念代万念、一念不生，精神内守，外不可干。如此，生活即修行。
楼主：星空迷航  时间：2016-01-28 23:28:39
大脑是人体指挥部，身体的日常运作中心(心是生命活动中心)；需要消耗很多的能量，供应不足时人即疲倦了，故有睡眠。
睡眠有浅睡、深睡、沉睡。身体休息了，但心灵没进入静态，所以出梦了。真我游行，本我旁观。
真我纯洁，没有外在的欲，朴而信。在引导中，卓渐完善进化。
楼主：星空迷航  时间：2016-01-28 23:33:02
入睡前的欲念，就会通过本我，影响到真我。
手心和手背。
楼主：星空迷航  时间：2016-01-29 00:07:33
藏密，六成就法之一，梦关成就法。为西藏噶举派(白教)24代祖师柏玛迦尔波喇嘛所创。
清醒、做梦、睡眠均为人类意识形态。人们受环境的刺激，产生喜、怒、哀、乐的种种梦，千奇百怪，颠倒流转，一切情绪会在梦境中发泄出来，但许多梦却在清醒后便遗忘了。
对于修行人，白天思想容易自制，夜间，思想任意奔驰，梦境颠倒，无明、爱、憎等不易控制，对生命和修持都有影响。
藏密的梦观成就法，把白天和夜晚两种不同意识形态下的修持，连接起来，脱离梦幻颠倒 。
修持梦观成就法，要求达到明悉梦境，转变梦境，认识梦境为幻变，禅定于梦境之实相，即在梦境中明心见性。
楼主：星空迷航  时间：2016-01-29 00:26:38
明悉梦境法，由睡前姿态、上师相应法、睡前观想法、醒后观想法。
睡前姿态，睡姿，为右侧体卧(心脏在左，不压迫)，如狮子卧姿。以右手大拇指及无名指，轻轻抵压喉部颤动之脉管；另用左手手指放在鼻孔的出入息处(不是压住，而是放在鼻孔前方)。
睡梦中，j口要合起来，不可张开，要合口津液(口水)不能外流。
喉部神经丛是控制梦境反射的所在。
楼主：星空迷航  时间：2016-01-29 01:33:57
转变梦境法，可举例说明。如梦中见火，当自思梦中之火有何畏惧？如是坚定自信，足踏火上。
藏密，梦观成就法，能对大家有帮助，易行的睡姿与转变。可以参考。
如要修梦，则需仔细阅读帖子，明白自性。
楼主：星空迷航  时间：2016-01-30 00:46:11
今天上天涯，已经不容易了，所以迟到了。我的守护，已经不停的警示。现在已经有两处注意上了，试探追查的好自为之。2016年，虽然存在危险，但仍然是快乐的一年。
楼主：星空迷航  时间：2016-01-30 01:17:24
仔细的查了帖子内容。唯对诵真经，可能有误。修心之初，人们身带尘息，所以诵经、诵真言、诵咒都可以。但真言、咒就像武器，不能常持；咒、真言，都带有别人的印记，最适合创立者使用。部分带有印记的经文，也是因此。
真经，是修行通达彼岸的觉者，留下的对大道的体悟，指引后来的。如是这体悟经文中，带有有印记，则是真言。
真经能让后来的，直接体悟，都适合。真言、咒，只适合初期洗去尘息，或者用之为武装。因为，这是借用，不是自己领悟的。如是没有印记，借用过来就是自己的了。不过，修行初期，付出的对自己影响微。所以，明白自性后，改修真经。
自性觉醒，您就能判断对错了。也能掌握度。
修行初期，自性觉醒之前。
楼主：星空迷航  时间：2016-01-30 01:44:54
您喜欢的经书，最容易相应，洗炼效果也快好。洗去尘息，您会一下感到心灵放松了，能提高适应能力，提高应变能力。
楼主：星空迷航  时间：2016-01-30 23:58:54
既然有凝，我再释之。修炼心灵的我，敬神、但不信神，敬仙、但不信仙，敬佛、但不信佛，敬地、但不迷地，敬天、但不迷天，敬道、但不迷道。因为人人有神性、有仙性、有佛性、有道性。我就是我，万物皆为友，平等。
上述道理，帖子本来就内贯穿隐藏，今有凝，本意愿大家从帖中悟。
仔细阅读帖子，就像我来应，或许也是一种修炼。就是您已经具有大能力，或许也能从中获益。
楼主：星空迷航  时间：2016-01-31 00:20:29
何为真经？仔细读了帖，应能自行判断了。但在这里需要补充一点，阴符经，从“观天之道……我以时物文理哲”此才为正文，人皇所作。内涵人道至理，后人能作早就为圣了，明白什么是“三返昼夜，用师万倍”吗？这是“真经”。相应状态下，就好像听见一位圣人，独立天地间，用淡淡的言语，阐述人道至理。
   
* 6
** ...

楼主：星空迷航  时间：2016-01-31 00:33:30
今天回帖三段话，用了一个半小时以上，卡卡卡…………
楼主：星空迷航  时间：2016-01-31 01:01:59
有人问我经历，我的不适合大家，只会干扰。想了解我的路，行，我精研过，易经河洛、道德经、黄帝内经、悬空风水、奇门遁甲、藏密佛经、导引术、武术内功、现代物理化学、道家经文、新兴的前沿科学、古医学……发现其中有共同的一个理，或许您们能见到某些的都不容易的。
曾经的经文，已被我遗忘，曾经的能力，也被我遗忘。悟道需要体道守一，研究需要破秘寻真……
所以，我能对帖子中的内容负责。
楼主：星空迷航  时间：2016-01-31 01:22:43
我已受限，今后不一定回帖大家，太费时。敬请谅解！此帖的引导，还余一步了，今时散金，愿来日能得友。
楼主：星空迷航  时间：2016-01-31 23:47:37
进不了天涯账号，我翻一下。试试入帖
楼主：星空迷航  时间：2016-02-01 00:07:13
……………一下就进了。……
补充下梦，解禁一些。人们通常入梦，梦里的您，手中通常都拿着一件东西，这个东西就是对您的指引。在梦中助您真灵进步的。
该放弃的，梦中自然能放弃，就是真心放下了。手拿武器的，对战，是锤炼无惧心。爬山的是锤炼，意志毅力，要坚决不放弃。梦入阴暗场所的，是也是锤炼无惧心，消除心灵上的缺陷。……
当您在梦中，能确认梦境是真实的，那么就破梦了。当您在梦中，能确认梦境是虚幻的，也破梦了。
可以把梦境当作一种信息提示。不过分追求，似真似假。
楼主：星空迷航  时间：2016-02-01 16:19:22
愿修心的，如有不明白的，反复读帖。，所有回帖中出现的，一点点不良信息，我都及时的加以了导引，故无虑。
如您已经有了大能力。欲重炼心，那么反复读帖吧。帖中已藏有多方面的信息，我已经开了线头，悟了就是自己的。
楼主：星空迷航  时间：2016-02-01 23:04:19
今天，挺顺。祝大家小年快乐，早团聚。
楼主：星空迷航  时间：2016-02-02 00:05:56
末世中，人们心灵最弱。因为，末世中，神魔争机，天劫、地变、人祸频发，人心起怨，人念起恶，心灵受五浊蒙蔽，对本我的支持不足时，本我可能受染，影响心灵的成长。故，末世当修心！
楼主：星空迷航  时间：2016-02-02 00:14:50
末世，去欲存善。去欲，可消念恶；存善，可祛心怨。
楼主：星空迷航  时间：2016-02-02 23:41:56
平静了几个月，这几天，大气中的怨力，又开始，微微上升了。
中华民族，忧患实多。自强吧，唯自强能自救。
楼主：星空迷航  时间：2016-02-02 23:46:28
末劫来前，必有瘟疫。天瘟，必须心灵洁净始能不染。人瘟，为自强能多抗，某些中药也有抗力。
楼主：星空迷航  时间：2016-02-03 23:33:04
人死而灵不灭，会进入地球母亲的四维体中，生物量子界。传闻中的地狱、天界、极乐净土等等，都与此相关，不过亦可称之为灵界。所以，神仙魔传闻N年，只能显灵，不能在现实界显身。
所以，人身最难得，唯人身才能超脱。所以，众灵都摹人身。但得人身又最易暗昧，最易堕落，忘了前示。
楼主：星空迷航  时间：2016-02-03 23:55:20
欲盖顶，而无机。今天说说第四维。
前面提到，人身含有第四维度。但是，不像三维那样被人们所掌控。三维是线性结构，以面展开；第四维是膜结构，以原体展开，表现为能场。
武术修行中的硬功，比如铁沙掌，通过反复锻炼身体部位，血气充溢，四维变增，在经固化(药物等)，掌控部分的四维力量。
此已远帖。悟之者请珍之于正用。明此，当知修心灵，是大方便，众灵亲之。还在凝惑的，坚定信心吧。
楼主：星空迷航  时间：2016-02-04 23:34:03
知其白，守其黑，可以为天下式。
河洛，是华夏文明的源头，古人们推演，出易，后发展为道、医、儒，流派百家，这是传承源头。佛释，由外而来，生根融入，是派生源头。
古人传经，以明天道、人道、地道之理。心之所念，是缘起 。心之所存，是文明。此为华夏心源正本。
西方文化，与华夏文化，一阴一阳，合之成道。故修心灵，匆为外所迷。
楼主：星空迷航  时间：2016-02-05 01:18:19
或许，我对大家的期望太高。所以，很多都只开个线头。是我有误。
末世中，本就迷雾重重，来之不易。
三才天地人。凡有情众生，衍生天地间，皆属人道，故精物修行，炼体化人。
人，为万物之灵长，本人道。故道，传人道，有理可循；传天道，雾兮渺兮；传地道，德敏心空。
人道至理，乃阴符经。所以，在这里提出个建议，加诵阴符经。比如，我喜金刚经，那么可以分个时段，诵阴符。诵真经，应分时，勿突连(本部可重)。因为各部真经，所展现的道、所展现的至理不同，形成的意境不同。
楼主：星空迷航  时间：2016-02-05 01:29:40
初修行，体悟人道，可加深对天地的感悟，对自然的理解。但不提倡。因为，我也可专修一经，觉醒了自性，再修其他，最终走向超脱。
楼主：星空迷航  时间：2016-02-05 01:34:55
不是我的建议最好，而是在这种建议下，您选择出与自己相应的，才是您所需的。
楼主：星空迷航  时间：2016-02-06 10:19:08
以前十年难得一次。进来几乎天天或隔天就有的地震，会持续吗？
回首四顾，是忙碌于过春节的众生，尽管天地间清冷。
频繁的地震，是异像吗？已没人惊讶。只有维真之人，在悄悄的准备，为了家人。
楼主：星空迷航  时间：2016-02-06 23:14:12
今年的春节，远方的人们回来了，但静静的，空气中没了去年的活力。生活依旧，饿了吃饭。
楼主：星空迷航  时间：2016-02-06 23:22:36
大气中的劫气，仍在微微上扬。修行吧，改变从自己开始；修心吧，唯有强大的心灵才能运控强大的力量。
觉醒吧，唯有觉醒了自性，才能不受外在意识形态影响。觉醒了自性，才能慢慢的了解这个世界的真相。
   
* 7
** ...

楼主：星空迷航  时间：2016-02-08 00:32:11
祝大家猴年中奋起千钧棍，劈出一片新未来
楼主：星空迷航  时间：2016-02-12 00:16:37
补遗：
来此接受引导的人们，有的自性开始觉醒了，有的以初步接触到五维心之力量。为此，特为您们一个自我武装法门，以未来为助力。
意针法：修炼心灵的人们，更易在脑部，感受到一种场，是人们思维活动的力量基础，可以称之为精神力或念力或神念。
心灵平静状态，澄心，集中意念，化为一颗针或盾；想清楚后，散而归源。
以自然为度，不必追求。不定时。
楼主：星空迷航  时间：2016-02-17 00:00:58
今天来查了帖。我有些建议，在某些灵魂被金钱腐蚀了的居高位的，利用国家的系统，将某种人瘟潜伏了，中药中的甘草、板蓝根、黄芪、犀角、大黄等对部分的有一定抗性。存点吧，今后可能有用。
楼主：星空迷航  时间：2016-02-19 00:03:14
缘起。
认识自我。日日反省。
当前的人们，难以做到修行需要的静态。为学习工作奔波，多虑；追求金钱美色，多欲；身体劳苦，损精；争斗多思，损神。思念纷飞如天马，心中念头如猿猴。不得已，故修行入门难。
特别是古法修行，需要入静态，惟精惟一。所以古人修行，是专业。今人需要工作食住，每日精损神耗，难以入修行状态。所以古之修行功法，在今人难以入门。就是在古时，选个传人也不容易。所以，需要适合今时的，方便法门。
特别是现今于末劫时期，外界染力重，故在此推荐大家修心。修心，能纯洁意念，净化心灵，培修损耗的神及念。打好根基。
诵真经，以真经为念，心应真经意态，自然能锁心猿栓意马，入修行人的静态。
楼主：星空迷航  时间：2016-02-19 00:17:54
此中真意为谁知，三千大木结舟时。艄公请来不上船，自语此身不慕仙。哈哈哈
楼主：星空迷航  时间：2016-02-21 23:16:31
元宵节了。
同看天边月，有圆有不圆。
楼主：星空迷航  时间：2016-02-22 19:47:06
现在是道德沦落的时代，污染了，不要紧，奋起吧，修心吧，跃出苦海，唯有慧心作舟。
坤上乾下，木陶开花。复我旧裳，君子有何 。
花上您娱乐中之一点点时间，修心吧，穿上心灵武装，外御百邪。
楼主：星空迷航  时间：2016-02-22 19:52:07
今天后两年中，每周六的晚上7：30至23点，我必来贴，为大家答疑。
楼主：星空迷航  时间：2016-02-24 01:52:43
(超出了，重打，麻烦)第四维是膜沿球心发散或收缩。证明第四维存在的，如各类场。最典型的事例，电子绕原子核运动，全向性、高能、无规则形成科学家说的电子云，就是第四维膜。恒星的外界膜。
当然，像三维的线一样，线可以是直线，成方体，也有曲线成异体。膜能成球面，也能成圆筒(管状结构)。这个膜，如能级轨道的，像电子云；实物的，像水球膜面等。能力中的搬运、穿越就与第四维相关。
第四维中运行的能量是生物量子能。我们从食物中吸收的化学能有机物，除供身体代谢外，都转化为生物量子能，供心灵活动需要，特别是大脑思维。所以，思维活动越是发达的，消耗越大。靠三维中物做能量供给，难以保障，故人们用脑过度非得长睡。人睡眠就是因此。
常人，三维供给，所以很多基因缺能，进入封印状态。修行人，打开了第四维，有了更高效的能量来源，故能激活身体封印的部分基因，产生功能或能力。
第四维，在人体中如中医的经络丹田，瑜伽中的脉轮，算四维通道；整个人体由四维能场包裹。平常人，第四维是被动的运转，效率十分低。
能力很大，四维体没形成，仍然难得长寿。
严新，那曾经是我崇拜的对象，在江油也过了几个年。古代修行体系，已经不适合当今了。
楼主：星空迷航  时间：2016-02-24 02:46:41
像严新大师，甚至很多大德，不知道他们见证到宇宙真相没。虽然他们有大能力。不能超脱，活万年活亿年，与活一天没什么区别。我在这里做指引，是因为这届文明我是知道方向的，不得已。否则，哪怕功夫再高，能力再大，也只是在迷雾中探索。
人类能修行，万物都在修行，有些在开智之前是被动修而已。阴符经云：“天地，万物之盗；万物，人之盗；人，万物之盗。”
修行人称的蕪，灵气，可以说是天地的量子场，入体后，通过四维通道转化成自己的。末世中，修炼有成的灵比人类不少的。因为，他们更淳朴。
楼主：星空迷航  时间：2016-02-24 03:22:23
牛顿发明了万有引力，但造不出飞船；爱因斯坦发明了相对论，觉造不出原子弹。请尽量不要在贴子中暗示或提问中带印记，这个贴是为了指引有缘心灵修行，我想保持它灵性不染。在我眼中人和花草、动物没什么区别。
能力功夫，心灵提升了，今后时机来临，举手可得。大能力我也曾有，只是被遗忘了，那是能力障。
有缘的，唯有修心，容易脱劫。
不要轻信，不要自卑。因为信什么就是障，我们都是众灵入世，求进化，觉醒了仙性就能成仙，觉醒了佛性就能成佛，觉醒了神性就能成神。
楼主：星空迷航  时间：2016-02-24 03:57:51
众位大德，不过比我们先行一步。尊敬他们，以之为灯，好好修炼心灵。
楼主：星空迷航  时间：2016-02-27 19:43:35
报到了
楼主：星空迷航  时间：2016-02-27 19:58:47
我不知道有没有其他做心灵引导的。我开这个贴的目的就是，让大家觉醒自性。自性觉醒了，就能辨别是非，不会受外来信息影响。就能在生活中，选择始终对自己有益的方向。所以，其他只提提，不讨论。
楼主：星空迷航  时间：2016-02-27 20:11:58
准备讲讲信念问题。
楼主：星空迷航  时间：2016-02-27 20:53:55
一位女士，接到一个电话。说某地区月薪轻松万元以上，或者某投资月投入一元，年回报十元。(诱惑)
她一听，哎，可能吗(凝惑，自我保护)？同学，千咒万誓，证明是真的。你可以先过来看看呀！(下套了)
于是，女士请假去了。同学带着去了某公司，参会旁观 。(很为您着想)
到了会场，主持和全体，非常热烈的欢迎光临参观。然后，会议进入高潮。(掩知是备战待客)
成功者出击。穿得气派，态度温和。收入如何如何，一副成功人士气象。(吸引)
接着，公司发展介绍，月会议报要，上月如何如何。(形式大好啊，快来加入)
老员工经验介绍。公司如何如何人性化，管理理念如何如何先进，生活如何如何大家庭，团队帮助如何如何，……总之，就是如何的好。(快来加入，入了公司一世无忧)
今天，会议结束。同学带着女士住宿。公司免费食宿。(好温暖的大家庭)
第二天，一个电话来同学，问女士去参加某活动不？结果去了。
是公司新产品销售活动。某项产品如何如何好，效益如何如何高，专业的财会计算，数字比较。(快来加入，利益好高)
第三天，参观。去了，新员工学习活动。新员工介绍，刚加入，取得了多少收入…。利益是如何如何有保障，对未来如何如何憧憬。
这时，同学问了女士。加入不？这些，都是真实不虚的。(关键的选择来了，是让您自己做的决定)
楼主：星空迷航  时间：2016-02-27 21:03:39
这是传销的过程。旁观者知道，洗脑成功了，进去就不愿意出来了。因为被同化了。一种外在的意识观念，潜在的代替了女士自有的意识，被操纵了。
女士忘了，“天上会掉馅饼吗？”，她不知道“交换是有价的”吗？因为她没心灵武装，因为她自性没觉醒，对外来信息难以理解。
楼主：星空迷航  时间：2016-02-27 21:04:51
难以做出对自己最有益的选择。
楼主：星空迷航  时间：2016-02-27 22:45:39
一位男士，一天，多年没联系的堂妹，带了个中年男子，来家访了。
堂妹说，某哥哥，打听到您喜欢修行，某老师知道了，今天同我来看看您。
某老师说，不要紧张，我们随意交流。接着他说了，一人修行全家享福，后面的事你们普通凡人就不要参与了。赶出了男士的父母及堂叔娘。
问了些普通话题，某老师看着男士的额说，你悟性不错，龙华会上应有名。现在三界收元，观音515工程已满，还在开启113工程，不要错过了回归之期。
第一次会晤结束。男士赶快找堂伯了解情况，说某老师多次转世，在东北、北京、南京等地都有坟，几百岁了，什么都知道，厉害得很。
不久，堂伯电话来了，说老师要男士的八字，很为难，男士做了三层加密给了。
不久，又来电话，老师直接让男士接了，说八字不对，从档案中提不出。
又不久，第二次，在堂伯家会面了。天气很好，老师一直在说，不要有压力，这次是专门来渡你的。龙华会上查到了你的名，你有两个引导师傅，一佛一道，为此专门去了地府，才查出你的八字，对上档案。
堂妹说，老师从来没这么看重一个人，您如不信，晚上修炼时可以问您师傅，他们一定知道老师的。我们不明白时，都只能问师傅，难得老师指点您。
男士说了话了，(恭谨)感谢老师挂念，不忘苦海中人。我觉得自己好像是另外一条线。
老师说，三界收元，就只有一条线，天上神仙都在劫，名字上了榜的才能回归。
你的引导师父是达摩，但达摩是我的弟子，这具肉身是我行走人间之一。
男士脉脉。
堂妹说，十大佛祖都是老师的弟子，哥，能得老师看重太难得了，您应了吧。
老师说，知道吗，你大师兄在北京，犯了错误我封了他，你二师兄办事不力我废了他的法力，你三师兄在成都办事，还不错。
男士脉脉。
很多人劝。
老师说，名字已经上榜了，不如我们门，就废了你。
男士说话了，“我真心不信，就没人能废我，神魔也不行”。在劝解。
老师说，悟性很高，“的确只有自己废自己”。我门一直开。老师让人拿了块碧玉方牌，中间有个玉兔。堂妹说，这是老师的身份，天下只有三块。
男士感叹说，感谢老师的挂念，我有个愿没了，老师您来早了啊！至少四年后我才能了愿。
吃午饭了，男士告辞。

楼主：星空迷航  时间：2016-02-27 23:00:59
关于信念问题，本来一年后才讲的。但上面有提到了大能者，所以写了信念的，是不愿大能们的名影响到这个贴的灵性，影响有缘的心灵修行。
* 8
** ...

楼主：星空迷航  时间：2016-02-28 03:20:58
英媒：转基因蚊子或系寨卡病毒爆发的罪魁祸首，广州已释放50万只转基因蚊子转基因观察 · 2016-02-04 · 来源：转基因观察
楼主：星空迷航  时间：2016-03-05 19:32:46
报道了，我先看看
楼主：星空迷航  时间：2016-03-05 20:40:14
看完了。可以回答的，做了引导。现在我们华夏，正能量已经压制了负能量，但是负能量正潜藏，谋划致命一击，分三步肢解我华夏。总之，他们不会成功。愿该小心的人小心，申酉太过，生路在西。
楼主：星空迷航  时间：2016-03-05 20:50:45
今天说说心灵。
人体进化，是往哪方呢？借此提提。生物经过进化，出现人体；人体再进化，我们这届文明，正在像形成四维体发展；四维体再进化，就是五维体心灵。
心灵、四维体、肉体是相辅相成。这就是，我们文明的三才。
楼主：星空迷航  时间：2016-03-05 20:56:43
印度、西藏有许多的苦修，一个动作会做上千万遍，就是为了把那个代表的意识规则，写入真我，掌控第五维那方面的部分能量。
楼主：星空迷航  时间：2016-03-05 21:02:47
修行慈悲心力的，行走天下救济世人；修行金刚心力的，默然世间；修行平等心力的，以大爱身传………
楼主：星空迷航  时间：2016-03-05 21:08:17
心灵，能接通第五维，但第五维的能量需要在心灵中有个引导源，才能过来。这个引导源就是，真我中您认为的。
楼主：星空迷航  时间：2016-03-05 21:09:58
今天的内容是17年或18的，大家要趁重。
楼主：星空迷航  时间：2016-03-05 22:27:55
真经除了诵之外，有没有人悟到其他方法。其实，您有多的空闲时间，还可以抄经。一心一意的抄经。
楼主：星空迷航  时间：2016-03-12 19:34:59
报道了
楼主：星空迷航  时间：2016-03-12 19:50:28
临渊慕鱼不如退而结网，万里之行始于足下。度人先度己，欲行外先明内，欲改变世界先改变自己。
楼主：星空迷航  时间：2016-03-12 20:56:45
今天释凝六字大明咒。
六字咒，缘起与密宗三字总咒(有称高能功，光能桩)，嗡(weng)、啊(a)、哄(hong)。嗡，接引宇宙能量临身；啊，能量洗涤身体；哄，能量排出体外，放无量光利他。
六字大明咒，把啊字化为嘛、哩、呗、咪荡涤身体。更易修行。
嘛哩，？语中意思是自性，呗咪，意思是莲花。
嗡，接引宇宙能量临身；嘛哩，荡涤自性，呗咪，洗涤集约能量；多余的能量同身体的杂质一起，被哄字，排出体外，利他。
这就是自我加持。
与念“阿弥陀佛”同理，是念者加持给“阿弥陀”佛。
楼主：星空迷航  时间：2016-03-12 20:59:10
所以，要正念，从真心起念。念头要淳。
楼主：星空迷航  时间：2016-03-12 21:33:43
举个例，赌博的人们，一围成桌，则成局成势，之后整个过程，必须按赌博的规则来(其他的身份、权力就没用了)。
修行的人一旦修行，在那个点就成修行规则。所以，与道、天、地相应，修行人最大。所以，一切的外源信息，都得通过影响您，才能干涉您。
楼主：星空迷航  时间：2016-03-12 22:10:26
目前，我已经看见，有一股能量在消除地球上的负面信息，不知损益。
楼主：星空迷航  时间：2016-03-16 20:42:12
大家好!有提问的吗？
楼主：星空迷航  时间：2016-03-16 21:59:04
我现在用的无线上网，速度要慢些。
楼主：星空迷航  时间：2016-03-16 22:45:04
这个帖子，以诵真经(相应)，抄真经(相应)，修炼心灵，是大方便大捷径。因为我们站在了先圣们的肩膀上。先贤先圣，历尽千难万险，传下众多真经。
楼主：星空迷航  时间：2016-03-17 00:45:42
与其清谈，不如做些实事。
楼主：星空迷航  时间：2016-03-19 20:41:12
对不起。我迟到了。
   
* 9
** ...

楼主：星空迷航  时间：2016-03-19 21:27:19
说说相应。
相应由念头和心力来体现。念头越纯粹，心力越强大，体现相应越和谐。
以军训为例。初期百人军训，站队衬之不齐，应声先后强弱不整，没军威。因为各人想法不一。经过一段时间训练，逐渐人心统一，形体(队形)一致，集众力一体，就显现出了威严。所以相应念头如军训，一体后念头统一，杂念就消除了。
楼主：星空迷航  时间：2016-03-19 21:55:35
心力，是心灵外用的体现。比如，外人骂人，被骂者会感到不舒服：骂人者以心灵意志，观想种种恶毒形态，以语言的形式，这种信息发出射攻击；被骂者，接受到攻击信息，心灵弱就会干扰本我，体现出心胸烦闷不舒服。被骂者心灵强，不良信息不仅入不了体，甚至被身体能场反射，倒回进入骂人者身体。偶有念头来也能被转化排出 。
排出不良信息，就是心灵成长壮大的过程。
世上能干扰本我的不良信息，又何多。与真经相应，就像训练心灵，排出不良信息，心灵与道相合得以成长。
过去范例少，所以佛说：可，是他，不可，也是他。
楼主：星空迷航  时间：2016-03-19 22:13:40
修炼心灵的人们，看世间。初，旁观，以心灵中真我为师；身在世间，心在世外。
楼主：星空迷航  时间：2016-03-19 23:32:20
某些人在危机时刻，会出现超常的力量，何也？因为意志淳一，心念淳一，在那个瞬间心念的力量打通了时空第五维。甚至出现超越几百倍的力量都是可能的。不过，在大的力量也要通过身体来体现，所以事后会很长时间才能恢复身体。
所以，人们常说：大难不死，必有后福。经过大难后，心灵强大了，念头纯粹了。修心灵的人们，不要被能力迷茫。积累吧！
楼主：星空迷航  时间：2016-03-23 20:42:34
万般修行皆为假，唯有本源是真道。大方便，就是直指本源的。假传万卷书，按万卷书修行，就易入假幻。什么是魔，追求外相者，最易通魔。入幻，把虚假当真实；入魔，追求虚假的。修行路上无捷径，但有大方便。
楼主：星空迷航  时间：2016-03-23 20:45:25
明辨自己。正念从心出，邪念从脑(意)出。外相，通过意撼心，是谓魔劫。
楼主：星空迷航  时间：2016-03-23 20:47:45
正念和邪念。正念是真我发出的念头，邪念是外在不良信息，因六欲而染，与身体七情某些结合，操纵本我展现出的念头。故，邪念是以外在利益为上；正念是以内在利益为上。六欲不生邪难付，七情不动邪难留。降伏了，就是一个念头而已。降伏不了，就成了附体。
楼主：星空迷航  时间：2016-03-23 21:48:35
修行之路或超脱之路，好比一颗大树。众生沿大树而行，但到了一定部位，大树有了很多的分枝，直通树巅的只有一直沿细小的树心前行，进入树枝前行的能到枝部的顶。
到颠的，能通大道。到顶的，只能得到果位；果位，再次修行的一个基础。
众生都认为自己或流派修行的是大道，而直通树巅的大道只是一条很细小的路，一条曲折的路。迷失方向的，能达树顶的，就只能证道果位。故，千百年来，各教通天的，除开创者外希矣。
待明白果位，开了心眼，修行路上觉难以回头。
红尘是个大染缸，但也是锤炼心灵的好地方。尘俗之力，挑动六欲能让人坠落，也能锤炼本我让真我进化。
明晰自己，分清正邪，破除迷雾，了解什么是真我发出的第一念头，唯修心灵。
楼主：星空迷航  时间：2016-03-26 20:17:36
登录中……终于上来了
楼主：星空迷航  时间：2016-03-26 21:00:30
再次讲一讲梦。
前面说了梦是修心灵的，真我进化的一种指引。在梦中能唤醒人们潜藏的能力，确使真我完善。唤醒了并不意味着您就理解了，掌握了。还需要陪护，玄之又玄，众妙之门。
许多人，常常做某一类或同一梦，就是让人从真心觉醒，相应的门。当您在梦中某一瞬间爆发，觉醒了，那么这类梦就不会再出现了。
觉醒了，只是您具备了打开某种门的能力了。还要在日常生活中继续陪护，才能下次唤醒，唤醒一次这种能力就会得到成长。直到您能真正观察到，进入玄的世界，最终到掌控。所以，觉醒了，才是开始。
楼主：星空迷航  时间：2016-03-26 21:04:52
在现实中觉得某种场景好熟悉，那么真我提醒您，曾经已有个相应的引导，这种场景能对您的某种能力成长，有帮助。
只是人们没有明白。所以，没人珍惜。
楼主：星空迷航  时间：2016-03-26 21:25:38
在梦中，常常手中会出现某种东西，这是引导。其实还有其他的指引。
梦境中，是真灵主事，不明白人世心机，所以很淳朴。那么，您又怎么明白了梦境中的物事呢？
自性觉醒或临近觉醒的人，会感知到，在梦境中好像一直有一个指导，在您的意识外，不断的将梦境中的物或事告诉您。
您见物体，会告诉您此物的来历作用等等，就好像一下您就明白了。
如此。
这就是引导我们真灵进化的指导灵!所以，梦是专为真我进化服务的。但梦的世界，真真假假，假中有真，真中存假。所以，也是一种信息通道。
颠倒梦境因此。
楼主：星空迷航  时间：2016-03-27 00:45:04
每一种真经都相应一种道之韵律。
楼主：星空迷航  时间：2016-04-02 19:31:59
报道来了
楼主：星空迷航  时间：2016-04-02 20:05:05
当您们觉醒了某些方面，并在某种状态(愰兮糊兮)下，与天地相应，那么您们提的问题就是应该的，回答这些问题不会受天意处罚。也就是说，时机成熟。
为人的欲望，是没有此境，故需辨别。向上的，真心内发出的，可以成为成长的源泉。消极的，外在信息感染发出的，需增别，该转化的转换，该消除的消除。并非外来引起的欲望，都是不良。
楼主：星空迷航  时间：2016-04-02 20:40:20
什么是功德？，功，利他行为；德，行为产生的结果。做善事，有善功；把该善事行为，贯彻到下一个循环，得善果。
行善半途而废，会怎么样呢？做了善事，有善功。行善的对象没继续到下一个循环，没善果。该对象在被行善至下一个循环间，产生的因果则需要行善人分担。所以，很多人们行了善，而得恶果。如此。
楼主：星空迷航  时间：2016-04-02 20:49:49
所以，好心做了坏事，得了恶果。是因为，人们看不见事物的真相。
我们的世界是循环的。狼吃羊，是合理的。每种生物都能在这个循环中，产生出利他的一节。没有利他的一环，就不能成为循环了。所以，善功生焉。
进入循环了，就得到结果了。善德出焉。
楼主：星空迷航  时间：2016-04-02 20:56:58
要明白事物的真相，需要觉醒自性，觉醒不灭的真我。从本位出发去看世界，是难以看清楚真相的。身在世间，心在世外。所以，人们常说：旁观者清。
修行，有一环，排除不良信息，利他。何也？在修行人体内是不良信息，但对下一环节的众生，有可能却是最好的资源。
楼主：星空迷航  时间：2016-04-06 19:58:43
初修行者，怎样辨别信息好坏？除了真心做指引外，还可查看灵机。
信息入体，灵机清秀活勃的，热感之类的正性感悟，则是有益类。信息入体，灵机浑浊沉静的，寒冷惊凝之类感悟，则是不良信息。
浊息入体，胸喉气机必闷，欲咳。闭息，忍之，身阳自起，炼化。
楼主：星空迷航  时间：2016-04-06 20:05:13
如能明悟，相应真经，持真言武装，则阳光一起，自然消雪。
   
* 10
** ...

楼主：星空迷航  时间：2016-04-06 20:14:31
不良信息感染身体，某些只能在很短的某段时间里，通过外源惊动您的心灵后，才有机会入体；某些只有您的心灵松动，诱惑本我才能破入自我防护能场，进入。
故曰：精神内存，邪不可干；正气内存，魔不能染。此之意也。
楼主：星空迷航  时间：2016-04-06 20:18:21
只要有外源信息，能动心灵(莫名的不安)，即可持咒，开起武装。
楼主：星空迷航  时间：2016-04-09 19:36:59
周六来了。
楼主：星空迷航  时间：2016-04-09 19:40:44
清明节后，天机变动。天地之间的灵性能量增加了很多倍，比如，从千分之一增加至千分之五。
楼主：星空迷航  时间：2016-04-09 19:52:29
周三，我看了，没提。因为，清明节后，我联系不上守护，准备本六封帖了，结果，中午告知，一直与我同在。
我身红尘一凡民，今世开悟我朝真。道树花开三千莲，不及树外赏花人。
楼主：星空迷航  时间：2016-04-09 20:10:25
关于信仰：
中国人的信仰是，华夏传承产生的超脱之念。这才是宇宙中的正信。
华夏传承，人修成仙，金仙，大罗金仙，圣人。所以，人人都有机会修成圣。大罗金仙级别，也称大神。
宗教，是立教人为了自己超脱而做的后手。所以，世界上所有的宗教，除了立教人，几千年来没再出现一个大比修者，因此。
信宗教者，不得超脱。这就是意识暗昧。所以，真圣，不立教。
华夏人人都想成仙，人人都有超脱之念。只是，很多人被外邪蒙蔽，难明自性。
楼主：星空迷航  时间：2016-04-09 21:11:23
今后，随着天机变换，会慢慢揭示更多的真相。许多都会与传统冲突，所以，有缘的朋友们，您们要冷静的看待，细心的比较，利用网络时代的优势，跨越知障。
楼主：星空迷航  时间：2016-04-13 21:53:09
今天，有提问的没
楼主：星空迷航  时间：2016-04-14 00:22:13
修行人对生活，积极进取，百折不挠。哪怕千难万险，总能寻出一线生机。面对世间，不回避。
楼主：星空迷航  时间：2016-04-16 19:33:05
先回复
楼主：星空迷航  时间：2016-04-16 23:22:44
生活就是修行，做好该做的事，相应在心就是瞻集资粮。修行有方向，故今可以凭真经做指引。
楼主：星空迷航  时间：2016-04-20 21:12:10
有人念着，今天来回复。提个建议，就是提问的人，请尽量把您的问题，用回帖形式，放在同一层里。我会就可以解答的回复。
因为，这个帖子，不需要顶楼，楼层越少越好，方便后来的看贴。
有缘来看帖的，请尽量从头慢慢细看，至第五页，基本上形成一个修炼心灵的整体。有凝问，多看细思，就能从帖子里悟出答案。
修炼中不明白的还可以等待周三(不定时)周六(正常必在)，作解惑。
还没行动的，何不以研究的态度，试试诵抄真经。临渊慕鱼，不如退而结网。
其中的缘由，帖子里已经解得很透彻了。奋起吧！唯有修炼心灵，能觉醒自性。
楼主：星空迷航  时间：2016-04-23 19:37:43
报到了。先看
楼主：星空迷航  时间：2016-04-23 19:58:47
今天说说最初。
古人云：千里之行，始于足下。足下，是出发点，是起点；但是，是什么原因导致“千里之行”呢？
这个导致“千里之行”的因，就是修行者的启愿。启愿，决定了修行之初动力，也决定了修行之路，即修行法桥。
启愿，就是果。因愿生果，要化为真实的果，就需要努力修行。果一个，但达成果的路觉有很多条。不同的法，会形成不同的桥。但，能通向果的那条路，才是最相应的法桥。
楼主：星空迷航  时间：2016-04-23 20:56:36
人们常说，修行的，修道的，修佛的，修仙的，修真的。那么，有什么区别吗？
修，修炼。行，在路上。道，可道非常道，法则规律。佛，觉悟了的人。仙，山上之人，不在红尘中的人。真，真实，脱离了现象界的，真人、真佛、真仙。
启愿了，无量初生。根据愿望，生出分别心，亲近于相应法门，通过那些法门达成愿望。这就是，结缘。
破法见真者，难，少也。因为选择的法，如果不能达成愿，就难以形成法桥。所以，修行万千，大法难求，与己相应的大法最是难得。得到法门指引的，引渡了。
有了修行法门，可以修了。那么，又出现选择了。在哪儿修？有在红尘的，有在山水的，有这庙宇的。这是择地。择地最好与法门相应。
财和侶，与也是修行的得力。修心灵对财侶的要求要低得多。但财也是方便的一种，侶可相互交流鼓励，有利于勇猛精进。分别与否，选择在心。
楼主：星空迷航  时间：2016-04-27 20:28:28
说说身体。
修心灵，诵抄真经的不修肉身吗？
不是。肉体属于三维，量子能量体属于四维，心灵属于五维。起点不一样。
所以，打好基础，不要急于求成。这方面帖子里已经有说。开发出心灵力量，结出真种子后，返修量子能体，强化肉体。这是相辅相成的。
楼主：星空迷航  时间：2016-04-27 20:37:09
诵抄真经的辅助法门：频波震荡法。
身体或站立或坐，随意自然，站立从足下发力，坐从脊椎发力，使全身微动震荡。
楼主：星空迷航  时间：2016-04-27 21:18:18
心灵力量范例。
众人生活经历不同，初始容易启动的心力也有别。今以慈悲心力为例说说。
相应了慈悲心力，会感受悲哀情绪，排除身体委屈等负面情绪，或大哭大笑，或悲哀莫明。过去了，身体清凉，心灵生出(心令)(心敏)之意，慈悲心念出了。
在这种状态下，对于需要帮助的，尽一份心力，不必去管他真假。使慈悲之念，常持于生活中。此段过程，又称持念。
多帮助困难中的，在持念中慈悲心力会慢慢成长。
慈悲心力增长时，心灵会产生激动，特别是在帮助了苦难中的人们。这时，要牢记会而不用，心静下来，仔细感应心灵激动的原点。
慈悲之念增长，慢慢地影响身边的人们，暴躁人会久变温和，能化去周围人们的斗勇躁意，此时称慈悲之意。
继续休养，增长到能降伏动物的恶性时。可能会出现听见意外的声音等，不必理会。多感应心灵原点，感应到心灵慈悲原点，将慈悲之意慢慢凝聚于心灵，结成真种子。
有了真种，就可以做超度法事，解怨救苦救难。
此乃慈悲心力休养法门。
楼主：星空迷航  时间：2016-04-30 21:10:47
今天来迟了，对不起。请有凝问的朋友，修炼中有不明白的朋友，我在这为您们做解答。
楼主：星空迷航  时间：2016-04-30 22:06:11
今天说说一些常识。
在帖中，有很多女同胞，在修行。古代对此有很多忌讳。但修炼心灵，只按帖子引导就可以，男女一样，没什么。
我们世界由地、火、水、风、空构成。地，大地，五行土也，固相；火，能量，五行火也；水，生命的母液，五行水，液相；风，大气，五行木也，气相；空，时空，承载也。
宇宙由混沌演化出阴阳，清者上升，浊阴下降。阴阳继续演化四相五行，地球生命世界就由五行为基础。人类、动物、植物也由五行假合而成。
人的八字就是记录出生时，太阳系的天体运行状态，假为五行合八字。所以，八字能预测。
人体由骨、骨髓、筋膜、肌肉、血脉、皮肤、毛发构成，内有五脏六腑。
骨及骨髓，对应五脏的肾，六腑的膀胱，五行属水。
筋膜，对应五脏的肝，六腑的胆，五行属木。
血脉，对应五脏的心，对应六腑的小肠，五行属火。
肌肉，对应五脏的脾，对应六腑的胃，五行属土。
皮肤，对应五脏的肺，对应六腑的大肠，五行属金。
由上可见，人体从内到外，水生木，木生火，火生土，土生金。五行相生假合而成。金生水，则是身体由外而内，此乃修行之基。
其实，细心的朋友，当发现还有没说明的。人体进化中的器官。未来的第六脏，心包络；六腑的三焦。
   
* 11
** ...

楼主：星空迷航  时间：2016-04-30 22:39:46
人体，左为阳，右为阴；上为阳，下为阴；外为阳，内为阴。五脏，心肝为阳，肺肾脾为阴。气为阳，形体为阴。
对于自然演化，阳成气，阴成形。男子，属阳；女子，属阴。故男子阳气旺盛，精溢；女子精血旺盛，血溢。故古修行，男子炼精，化气归田；女子炼血，成精养形。所以，女子修行不易。
由知，精、血皆为生命之宝。人体的神、气全赖精血生养。
故修行有次第。
其一，炼己筑基。
其二，炼精化气。
其三，炼气化神。
其四，炼神还虚。
其五，炼虚合道。
其六，炼道归真。
过了炼精化气关，则寿可达六甲子以上。所以，万千修行人，过了此关的有几多？
楼主：星空迷航  时间：2016-04-30 22:49:01
古代修行，讲究出家，就是为了养精血。男女成婚，生育有子，则是男女之精血结合而成。
但是，修炼心灵，您成家也可，您清修也可。因为本帖子推荐的是修真道！不明白的多读贴。
楼主：星空迷航  时间：2016-05-04 20:52:58
今天来了，答凝。
楼主：星空迷航  时间：2016-05-05 00:26:05
玄之又玄，众妙之门。今天就此。
楼主：星空迷航  时间：2016-05-07 20:27:57
报道了。修行中有不明白的可以在这儿一起讨论。
楼主：星空迷航  时间：2016-05-07 21:00:28
大家百忙之中挤出一点时间来修行，可以在“百度的终南山吧”了解，有很多的修行人在这个吧里交流。
就当之为侶，以彼历程炼我真心。
楼主：星空迷航  时间：2016-05-07 21:21:56
我见证了真理，并不意味着真理就能为我所用，为我掌控。
只是明白了一条直通彼岸的路(这个帖子引导的就是)，所以我也得放下，重筹超脱之路。
按照以前的修行，爬过一山还有一山高，爬不完的山。尽管能足踏一座山巅，无论怎么爬，依然在地球表面行。
修心灵，就是积累力量，悟出飞越的能力。
楼主：星空迷航  时间：2016-05-11 20:38:31
学道当诚心、当敬道，始能近道。道不远人而人心远道，谈何修行？
诚敬于道，则能相应于道。诚敬于真经，则能相应于真经。诚敬于法，则能相应于法。诚敬于心，则能相应于心。
心唯真是道，心唯假是幻。但过千难万难，假能修成道，伪能修成真，天机自有一线。
可叹修行人万千，就是难过心关。
楼主：星空迷航  时间：2016-05-14 19:49:09
道是用来悟的，经是用来修的，身心是用来炼的。道德经云：上士闻道，勤而行之；中士闻道，若存若亡；下士闻道，大笑之。不笑不足以为道。
楼主：星空迷航  时间：2016-05-14 21:06:59
玄之又玄，众妙之门。修行人，一定多多体会自己的变化。身体变化，性格变化，心念变化。
有了同先前不一样了，就细心的体会，找原因，明白变化的缘由，这也是修，也是悟。从细处行，才不会走弯路。
楼主：星空迷航  时间：2016-05-18 19:39:38
又到周六了。
楼主：星空迷航  时间：2016-05-21 19:47:36
报道了。
楼主：星空迷航  时间：2016-05-21 21:53:52
我再解言：
诵，就是加持。加持在何处，相应于心。加持什么，加持真经或真言之孕涵的规则。
如嗡啊哄三字真经：嗡，接引宇宙能量入身；啊，能量在身体内震荡洗涤；哄，余下的能量排出体外利他。
控制音震节奏，嗡字长则有利于更多的能量相应而来，类似补益；啊字长则有利于身体锤炼吸收更多的能量(但能量由嗡字接引而来的)；哄字长有利于余下能量及不良的排出。
我再细言：
节奏，长短短N遍，短长短N遍，短短长N遍，最终以长短短N遍结束。
上述的几个N就是根据身体素质状态，和念诵的需要，而自我调整(也是一种相应)。
其他类此。
楼主：星空迷航  时间：2016-05-25 20:34:05
这个怎么分的页，太麻烦了。还不如先前的100楼一页，让人方便。
楼主：星空迷航  时间：2016-05-25 22:44:53
各位有缘的，无论何时，请敬守本心。不要忘了出发前的本意。
我再释凝：
有很多修炼武术或周天的，要将究开通穴位，打通经络。其实人体的任何穴位与经络，原本就都是通的。
不通则痛，则生病。打通经络的，其实是扩展经络，使其由羊肠小道变为通畅大道。真气运行经络，就像水渠过水，冲刷之后，能使附着物带走归田被生命之火烧去，保持水渠畅通。人体经络这个水渠，是由量子场构成的，它具有扩张性。
前面提到过四维体。其实四维体，每个地球生灵都是有的，只是没修炼的很弱小，不能主动外显。经过对应性的修炼后，四维体就能对外做功。
在我们这个世界，是存在着四维生物的。拳头大小的四维生物，口渴了喝一次水，也能喝去几顿重的水。
城市郊区或农村的人们，见证四维生物的可能性多一些。思维生物，随时随地都在放射出生物量子光，无论晚上或阴天，其光芒四射耀天。是一种能穿石过墙的实体生物，通常都居住在地下的地脉之中。
我们这个世界，秘密很多，明白了真理也没什么秘密。待今后有缘的到了这个层次在讨论吧。
楼主：星空迷航  时间：2016-05-28 20:11:14
前面提到过，诵经时，最好无念无想。在诵经中突然冒出个念头，这就是相应了，真经意态引动了真心，反映出来。积累不够是凝题，积累足了是感悟。或引出本我等受染的信息，或得预自然规则上的感悟，都是心灵成长的体现。
楼主：星空迷航  时间：2016-05-28 20:23:44
大家修行中有什么问的，可以提了。
当然，别人的问题我不一定答复您，好高骛远的，得看我心情，就是大家的心态。
这个世上的秘密我已观之，就是不知道的也可据宇宙法则推算出大慨。想知道就得好好修行，您们在修行过程中产生的，我会尽量仔细作答，根据不同人的悟性给出不同的提示。
临渊慕鱼不如退而结网。不同人们有不同心态，选择有不同的路，承受该承受的风光。
有句俗话说：平时不努力，急时抱佛脚。火出于木，祸发必克。晚矣晚矣。
楼主：星空迷航  时间：2016-05-28 20:24:53
生命孕育于母体中时，慢慢养出魂，待降生时得灵则诞生为婴儿。灵，天地某类规则的具现，万物皆有灵。
想：观想；非想：长时间自觉观想，如吃饭喝水；非非想：梦中自觉观想。
万物有灵，高功夫发出的外气也是有灵的。沟通万物，就是相应于万物。千里眼，透视遥视，心有灵犀，双胞胎的心灵感应，都是灵的相应。踩天地之灵气，就是与灵相应。
楼主：星空迷航  时间：2016-06-01 22:16:53
修心灵之余，有很多喜欢炼体的。今释古之真传关卡，使其明白路近。
炼体关卡：心关，水火关，轻重关，缓急关(滑利，涩滞zhi)。
心关，前面有说。
水火关：进入此关，或身如烘炉，寒冬穿单衣而汗流浃背；或身如寒冰，六月穿棉衣而颤钭。一般需厉2～3年。
轻重关：时或身体沉重，时或身轻如燕。
缓急关：时而身体滑利，行走如箭；时而身体涩滞，全身不利索。
上面是常见的炼体关卡，世俗难知，或浪费时机乱了心。渡过关卡，超能必然。
楼主：星空迷航  时间：2016-06-01 22:50:17
炼体的关卡，与人体七魄相关。七魄，是身体内七种力量之源，开启了，就能通外界，相应引入人体获得强化或超常状态。
   
* 12
** ...

楼主：星空迷航  时间：2016-06-04 22:56:29
请看帖的朋友，要把前后以及回帖的内容了解透彻。找到自己相应的。
比如，前面我有说：信教者难超脱，圣人不立教。对于有大愿的，或立志超脱，或追寻宇宙终极真理，或长生永恒的，或解危救难，建议别信教。不要走捷径。
对于愿脱劫脱苦超出五行的，无论修佛修仙修神，选个线路就是方便。
一切在于心。真不真？
楼主：星空迷航  时间：2016-06-08 20:37:31
祝大家端午节快乐！
楼主：星空迷航  时间：2016-06-08 20:58:56
端午节到了，本帖对心灵方面的初始引导圆满完成。
该说的，前面已经说到了。能相应的，敬请行之，有不明白的，仔细阅读或以真心为导，即能明白。
毅力，精进是修行的渡舟。劫前，每月周六，我会尽量在。
吾劫难结束，或许会动一动。
楼主：星空迷航  时间：2016-06-08 21:41:53
以金字塔镇楼。
金字塔，千古之谜。什么人建？有何功用，真的是法老之墓葬吗？
金字塔的建造，切合了很多的地球相关的数学之谜。众多的传说，跑、巧合，我不再赘述，借这儿破解其本质。
金字塔，是高级文明修建的星际量子灯塔。它的结构能让它工作百万年以上。
我以前计算过，大金字塔顶释放的量子能是地球其他地面的1万～10万倍左右，现在也能达到3000余倍。
所以，一切经过塔顶的飞行器都会失控。塔顶辐射的量子场，能麻痹损坏神经、五脏，对生物造成巨大的破坏。它就是一盏量子明灯，被掌握这类技术的文明，在遥远的星空做指引。
金字塔的构造，是按生物量子场规则建造的，所以，必须符合0·618规则。
金字塔原来的位置就是地球风水最佳处。它消耗了所在地区太多的量子场，四周就会干燥起来，慢慢成为沙漠。
守护金字塔的狮身人面像，是后来建造的,以阵守护下面的秘密，同时也是镇压东方,与东方的某个地方相应。
中华文化出现的狮子座像，就是外来的活阵，以别人的图腾狮子镇压中华的图腾龙珠。
楼主：星空迷航  时间：2016-06-08 21:45:29
我也懒得再开帖了。800楼之后，就作为杂说交流。想了解心灵修行的请仔细阅读800楼以前。
楼主：星空迷航  时间：2016-06-08 22:56:50
明日端午了。我就某些经中的特殊名词做些参解。
心经中的舍利子。舍利子，是自性觉醒的称谓，所以可以用世尊、如来、无量寿、无量天尊等同。
阴符经中的五贼。五贼，五行之意。
楼主：星空迷航  时间：2016-06-08 23:12:03
本帖初级心灵引导已圆满，更高的帖中也有线头的。所以，过了端午后，您觉得有指导意义，可以向您需要的朋友介绍，不再做限制。
楼主：星空迷航  时间：2016-06-11 19:56:46
……
楼主：星空迷航  时间：2016-06-12 00:39:51
昨日一艘外星飞船坠毁地球，国外媒体报道疯了。近来南极洲谷歌地图屏蔽了，有异常出现。天变不远了。
楼主：星空迷航  时间：2016-06-18 19:48:10
报道了
楼主：星空迷航  时间：2016-06-18 20:51:45
劫难的来历：
地球上的常规劫难主要是，来源于太阳系内的天体运行。
我们知道，人体或生灵的身体，都是由五行假合而成。人体有五脏，对应五行，肝脏属木，在方向为东方，在卦为巽，形气为风往来，在体为青色筋膜；心脏属火，在方向为南方，在卦为离，形气为红色焱上，在体为血；脾脏属土，在方向为中，在卦为艮坤，形气为黄色厚重，在体为肌肉；肺脏属金，在卦为兑乾，形气为白色锋锐，在体为皮肤；肾脏属水，在卦为坎，形气为黑色柔软，在体为骨。
楼主：星空迷航  时间：2016-06-18 20:57:35
所以，太阳系的行星，水星，金星，火星，地球，木星，土星，天王星，海王星。
这些行星的能量与人体是对应的。按规则，应该还有第九行星，还事9为循环，无九不成宫。还应有地十行星，数归于十，万物归于土，归土十也。
楼主：星空迷航  时间：2016-06-18 21:12:10
刚才吃饭去了，等会儿我在查看回帖。继续做资料：
月亮升空围绕地球为阴，太阳为阳。合前十星，成阴阳九宫法阵。
每个星系进化出的高级生灵，必然同星系的构成相关。经络气血的运行，更是如此。受天体能量场左右。引力只是天体对生灵产生影响的能量场之一。
楼主：星空迷航  时间：2016-06-18 21:21:09
所以，外星的高级生灵，必然是与其本星系相应的，身体构造和气血经脉必然与我们这太阳系人不同。
这些决定了生灵的潜力。
比如，某太阳系是18行星，其高级生灵据在星球有12个月亮。那么他们理所当然，认为最大数为18，算数就用18进制。在她们看来，这是非常自然合理的。
身体可能有18指头，每手九指。其它类似的推理，大家可以自己去推理推理。
楼主：星空迷航  时间：2016-06-18 21:26:03
从上所述，人体是被动的天人合一。无论您躲在地球哪里，太阳系的天体都会影响到您。
您的身体健康状态，您身体经脉的气血运行，都受它们制约。
楼主：星空迷航  时间：2016-06-18 21:41:32
华夏古传的60甲子记年，三元甲子记年，就是对太阳系天体运行的一种数学模型。
60花甲记年，近似是火星，木星，土星，天王星，海王星与地球的交汇周期。
三元甲子180年，近似是水星，金星，与地球的交汇周期。又暗合了前面五星交汇。故是大周期。所以，华夏古人，以三元甲子周转记年，也就能随时随地的了解太阳系各大天体的情况了。
古人，以天干，地支来表示星球的能量状态。10天干，代表10天星。12地支代表地月系的12种状态。
中国的人的八字，就是人体出生时太阳系的天体状态。所以，八字可以用五行推演，八字可以预测人的生命轨迹。其理源于此。
楼主：星空迷航  时间：2016-06-18 21:49:31
但是，这些周期并非就恰好等同，会有一定的误差。古人，就用润年润月来调整。更高级的是通过岁差运动来体现。像五运六气，奇门遁甲，就与岁差运动相关。
岁差运动，简单的地球的自旋与地月系，与人体五运六气相应。复杂的长周期，是用万年做影响的。
在这儿不细说了。
楼主：星空迷航  时间：2016-06-18 22:06:43
补一下：
十天干，甲乙丙丁戊己庚辛壬癸。甲乙，属木，代表东方；丙丁属火，代表南方；戊己，属土，代表中央；庚辛，属金，代表西方；壬癸属水，代表北方。
12地支，子丑寅卯辰自(打不出那个类似己的自)午未申酉戌亥。
寅卯，属木，东方；自午，属火，南方；申酉，属金，西方；壬癸，属水，北方；辰(东南)未(西南)戌(西北)丑(东北)，属土，土旺四方。
楼主：星空迷航  时间：2016-06-18 22:19:04
天体影响制约人体，同时，生灵合众，众心唯微，也反过来影响部分的天体。
末劫因何而来？所以，末劫是三元甲子运转，即太阳系天体运转，在某一段时间内，能量共振，对人体(生灵界)产生的影响。
人体是由五行化生而成。故天体产生的能量作用力(包含引力)，会对人体内平衡产生很大影响。相应在人体，就会无缘无故，很多人出现非常的念头(想法)。
这些想法中，少数修行的人能相应到好的部分。但大多的，因为普通人的能量场或能量等级低，难以存受，会出现过于激动、头昏、身体发热发凉、燥焖等异常状态。
心灵素养高的人，能控制自己体内出现的异常。心灵修养差的，就会很易冲动，成为恶行。
所以，末劫之时16～35年，人们容易造恶，特别是心灵素养差的要警惕。
所以，末劫之时，会有很多人，以为接受到了外星信息，要做神棍。
所以，末劫之时，会有很多人，认为自己被脑控了，有神啊。
都是心灵被外在力量影响，产生的幻念。
楼主：星空迷航  时间：2016-06-25 19:45:14
欢迎到来
   
* 13
** ...

楼主：星空迷航  时间：2016-06-25 20:48:48
继续上次，解释太阳系天地自然大阵。
前面说了太阳系的构成，以及天人相应的一些基本知识。
但是，太阳系的这类有什么特殊规则呢？各行星的运转距离，质量有什么秘密吗？我们继续讨论。
楼主：星空迷航  时间：2016-06-25 20:55:06
说太阳系行星的位置，我们要先了解一个规律——“体丢斯—波德”定则。
1766年,一位名叫体丢斯的德国数学教师在给学生讲述太阳系概况时,要求学生将各大行星到太阳的平均距离记住.可学生怎么也记不住这些毫无规律的数字.体丢斯仔细分析了这些数据,发现并非无规律可循.他先在黑板上写下一个数列,从第二个数开始,后一数正好是前一数的两倍,即：
0,3,6,12,24,48,96,192……
在每个数上加4,再除以10,便得到：
0.4 0.7 1.0 1.6 2.8 5.2 10 19.6 ……
水星 金星 地球 火星 木星 土星
以地球到太阳的距离为一个天文单位,其它数字正好是五个行星到太阳的平均距离,只有2.8个天文单位处没有行星,土星以后也没有行星,因为当时知道的最远行星就是土星.
体丢斯并没有认为这是个多么了不起的发现,不过把它当做一个教学生巧妙记忆数据的方法,所以当时没有传开.直到1772年,德国天文台台长波德发现了它,觉得很有意思,才将它发表.因此一般称它为“体丢斯—波德”定则.天文学家就是以此为线索发现了天王星,后来又发现了介于火星和木星之间的小行星
楼主：星空迷航  时间：2016-06-25 21:31:00
前面我们提到过河图洛书是宇宙的数学模型之一。
就此来分析与行星质量的关系。
楼主：星空迷航  时间：2016-06-25 22:10:54
中国人古传：河出图，洛出书，圣人则之。
有龙马自黄河而出，背负“河图”；有神龟自洛水出现，背负“洛书”。
人祖伏羲氏依图画象，创立八卦，开启了中华民族的文化之源，才有了后来的易文化。易者，日月相连而成，变化之道。
在夏时代，总结出<连山>易，山之出云，连绵不绝。把山放在了首位。那时候，大地上水灾患难、气候潮湿，人们只能选择高山住宿，所以，对大山很敬重、有了深厚感情。在文明记载中，自然就把山放在了首位，八卦排序尊山，故有“山之出云，连绵不绝”为开篇。
治好了水患后到了商时代，随着人口增长，吃饭成了主要问题。五谷种收，都靠大地，特别是主要食物，都靠大地养育，人们敬侍大地，八卦排序，就把坤放在了首位，形成了<归藏>易文化。
到了周时代，家天下出现了，阶级次序严谨，天尊地卑，首领代天牧巡，故称天子。八卦排序就把乾放在了首位，形成了卜祭祀的《周》易文化。
在秦始皇焚书坑儒之前，“连山易”、“归藏易”、“周易”又通称为三坟。
那么在夏时代之前有没有易文化呢？肯定有的。
楼主：星空迷航  时间：2016-06-25 22:25:39
…一刷新，前面的内容得15分钟之后才能看见。
易经的来源就简说到此了。
由此我们知道了，河图来源于天地相应的自然符文。河图洛书的图，大家百度下或书上查看。
以文字来述说河图，即古人云：天一生水，地六成之；地二生火，天七成之；天三生木，地八成之；地四生金，天九成之；天五生土，地十成之。
楼主：星空迷航  时间：2016-06-25 22:35:39
“我要是告诉您，通过之上的口诀古人可以轻易的计算太阳系八大行星的公转周期，轨道半长轴，甚至星体质量，您会相信吗？
但这却是事实。
首先拿出计算器，我们来计算‘地二生火，天七成之‘。
数字7的反比平方为2.6457……（2.6457∧²=7）；而数字2的反比平方为1.4142……（1.4142∧²=2）。如此，我们按照‘地二生火，天七成之‘的指引，用2.6457除算1.4142，得数：1.8708……。
而后再乘积1.006，得出1.88205……，也就是火星的公转周期1.88205/年，换算大概为686.94/天。
为了方便大家的理解，之上的计算列式为：√7÷√2×1.006≒1.88205/年。
方法及其的简单，如果不考虑常数纠偏问题（地球公转周期并非是准确的365天），甚至连之后的1.006计算可以省去。只需要按照古人的指引，‘地二生火，天七成之‘去计算就可以。
如果您还不信，我们继续计算。
首先需要颠倒运算关系，天三生木，地八成之。
√3／√8×1.006=0.6104……而天文学对金星的观测结果同样为0.61地球年，约等于224.7/天。
之所以要颠倒运算关系是因为，在传统文化中奇数为阳，偶数为阴，我们最开始计算的‘地二生火，天七成之‘关系，要求算的是偶数，所以奇数除算偶数。反之在计算‘天三生木，地八成之‘等关系时，便需要用偶数除算奇数。
这个规则是固定不变的，大家一定要牢记，因为在之后的运算中我们还要反复的运用到此类规则。如老子在道德经中所言：大道泛兮，其可左右。我们所在的世界并不单一，有某个互为镜像关系的平行世界，如同线绳般牵动着我们的世界共同前进。我们所在是物质世界，属阳；那个世界是反物质世界，属阴。两者叠加共存。
但其实，双世界叠加也并非是时空的真实样貌，时空也不是简单的二元对立关系，而是三世界叠加。对立转化关系，以十数合五方，如此维持质能守恒循环。
先别急着质疑，我之前说过，通过河图我们可以计算出很多东西，甚至包括连科学手段计算起来也颇为麻烦的各星体质量单位。请看完结果再去质疑好吗，数字不会说谎，也不要轻易地蔑视自己的祖先。”
此楼上述内容，摘自天涯杂谈“真是惊仙”帖子“中国古文化的神奇，河图洛书竟然是上古文明的天文学星图与计算公式！”
想要仔细了解研究的，可以去查看。
楼主：星空迷航  时间：2016-06-25 22:50:08
我们前面讨论过，太阳系是一个大阵，即在太阳系出现之初，自然运转就会按照大阵的规律分配各个行星。
这个运转规律，可以简化为河图洛书。老子在“道德经”中也提到过：道生一，一生二，二生三，三生万物。
也就是末劫之后才能讲的宇宙量子化规律2131原则。
有兴趣的，可以由上述提示，自己分析。
楼主：星空迷航  时间：2016-07-02 19:46:25
又到周六了。
楼主：星空迷航  时间：2016-07-02 21:58:22
我先回答下864楼。一会儿，接着前面讲。
楼主：星空迷航  时间：2016-07-02 22:51:53
继续说河图洛书：
河图 ，上方第一排7个圆圈 ，第二排2个黑点；左面外8个黑点，内3个圆圈；右面外9个圆圈，内4个黑点；下面第一排1个圆圈，第二排6个黑点；中间5个圆圈，上下各有5个黑点(合为10)包围。
黑点，视为阴数， 圆圈，视为阳数。
上方，视为南，2、7为先天火，7阳火，2阴火。
左面，视为东，3、8为先天木，3为阳木，8为阴木。
右面，视为西，4、9为先天金，9为阳金 ，4为阴金。
下面，视为北，1、6为先天水，1为阳水，6为阴水。
中间，为中，5、10为先天土，5为阳土，10为阴土。
上述为河图的数理。这里吾揭示一些书上或传承中很难看到的一些规律。
五行的运转，水生木，木生火，火生土，土生金，金生水。
但是河图表现的是，水生木，木生火，火生金，金生水，以中央土承载之。故是土承载四象。
相应于天地，则大地上有春夏秋冬四季，土旺四方。
楼主：星空迷航  时间：2016-07-02 23:03:23
河图中，阳数，1、3、5、7、9，阴数2、4、6、8。
阴数逆行，左8、下6、右4、上2。阳数顺行，下1、左3、上7、右9。加入5、10则阴阳皆不能归位。故土承载四象。
这里面有千古奥秘。
楼主：星空迷航  时间：2016-07-02 23:55:11
再说洛书：
4、9、2
3、5、7
8、1、6
洛书是说后天数像。东方，阳木，数3，在卦为震，雷，胆，筋，在色为绿。
东南，阴木，数4，在卦为巽，风，肝，膜，在色为碧。
南方，火，数9，在卦为离，火，心，血，在色为紫。
西南，阴土，数2，在卦为坤，地，脾，腹，在色为黑。
西方，阴金，数7，在卦为兑，泽，肺，皮肤，在色为赤。
西北，阳金，数6，在卦为乾，天，头，圆坚硬，在色为白。
北方，水，数1，在卦为坎，像为水，肾，骨髓，在色为白。
东北，阳土，数8，在卦为艮，像为山，胃，三焦，在色为白。
中央，合土，数5，流转居合之处，在色为黄。
楼主：星空迷航  时间：2016-07-03 00:28:48
洛书中三数为行，任意行三数和为15。4+9+2=15，3+5+7=15，8+1+6=15，4+3+8=15，9+5+1=15，2+7+6=15，4+5+6=15，2+5+8=15。
按顺序任意组数，其和不变。
29+94+42=165，35+57+73=165，81+16+68=165，43+38+84=165，
95+51+19=165，27+76+62=165，
45+56+64=165，25+58+82=165。
三数：492+924+249=1665，357+573+735=1665，816+168+681=1665，438+384+843=1665，951+519+195=1665，
456+564+645=258+582+825=1665。
按顺序，组四数、五数、……N数都会和不变。有兴趣爱好，可以推演。


楼主：星空迷航  时间：2016-07-03 02:12:09
续洛书数理：
平方^，单数，只有两组对应，即
4^+3^+8^=89=2^+7^+6^
4^+9^+2^=101=8^+1^+6^
复数，按顺序对应上面两组每组循环不变：
49^+92^+24^=81^+16^+61^=
43^+38^+83^=27^+76^+62^=
再有就是把洛书九宫图，用行列式计算，能得到一个周天数360。
det[4，9，2；3，5，7；8，1，6]=360
楼主：星空迷航  时间：2016-07-03 02:29:38
天地定位，山泽通气，风雷相搏，水火不相射。
故洛书后天也，1、6合水阵，3、8合木阵，4、9合金阵，2、7合火阵，5、10合土阵。
金生水，7=6+1；水生木，1+10=3+8；木生火，4+5=2+7；火生土，7+3=10，2+3=5；土生金，10+3=4+9。
从上述数理变化中领悟出或加深阵道变化的朋友们，请珍之珍之，慎之慎之。
楼主：星空迷航  时间：2016-07-09 19:49:28
来了。我先看帖
楼主：星空迷航  时间：2016-07-09 22:20:49
就8金字塔构造：
金字塔有两个重要的地方，其一是塔顶释放的量子能，可以利用来调节功用；其二是塔内中心的三分之一处，聚集了量子能的风水点。
说到金字塔，就必须明白黄金分割。把一条线段分割为两部分，使较大部分与全长的比值等于较小部分与较大的比值，则这个比值即为黄金分割。其比值是（√5-1）：2，近似值为0.618。
这个比例被公认为是最能引起美感的比例，人体的曲线，肚脐的位置，躯体与身高都体现着黄金分割。
自然界中的山脉走向，江河水道，风水结穴也得符合黄金分割原则，即0.618原则。
金字塔，按黄金分割，则得到的斜面角为51○52'。自然界中，在大风中存在下来的沙堆，就是这个角度。这也是集沙堆积的最大角。
其根源就是黄金分割原则，能量共振的最佳配置。
所以，在制定辅修金字塔时，最好把自己身体数据写入，达到产生的量子能是最符合身体频率的，最相应状态。
可以用铜丝做棱，四边，四棱，形成四个三角形。用三层或五层的纸板，剪切成四个三角形，粘连成一个简易金字塔。
金字塔的边长，与身体四极(四肢)相应，根据放置位置，取三分之一或几分之一。或者写入自己的身体重量数据，或者写入八字等等。
最好置于地面，量子能离开地面会散溢。
睡觉时，可以放床下，塔尖对需要调理的背部穴位，或者修行的脉轮。
通常能够补偿人体的生物量子能或生物磁能。使人头脑清醒，精神振奋。
有异常时(基本上不太可能出现)，要及时移开，仔细分析成因。
楼主：星空迷航  时间：2016-07-09 23:57:49
道家六字诀：
此乃道家调整五脏的辅助行功，也称服气吐纳诀或“修真六字诀”。
六字分别是“口四”(读如“丝”字音)、“嘘”(读如“虚”字音)、“呵”(读如“喝”字音)、“嘻”(读如“西”字音)、“吹”、“呼”。
楼主：星空迷航  时间：2016-07-10 00:41:24
功诀：
春嘘明目木扶肝，夏至呵心火自闲，
秋(口四)定知金肺润，肾吹惟要坎中安，
三焦嘻却除烦热，四季长呼脾化餐。
切记出声闻口耳，其功尤胜宝神丹。
六字配五脏歌诀：
心配属呵肾属吹，脾呼肺(口四)圣皆知，
肝脏热来嘘字至，三焦壅处但言嘻。
六字行功图录：
肝若嘘时目睁晴，争知肺(口四)手双(敬手)，
心呵脑后高叉手，肾若吹时抱膝平，
脾用呼时须撮口，三焦客热卧嘻嘻。
行功准备：
扣齿三十六，赤龙搅水津，
鼓漱三百六，神水自调匀，
一口分三咽，汩汩向腹行。
“扣齿三十六以定神，先搅口中浊津，漱练二三百下，候口中成清水，即低头向左而咽之，以意送下，候汩汩至腹间。”
楼主：星空迷航  时间：2016-07-10 19:23:19
决意解释：
一、六字释义
(口四)字：(口四)主肺，肺连鼻。受风即鼻塞，有疾作(口四)，吐纳治之。
呵字：呵主心，心连舌。心热舌干，有疾作呵，吐纳治之。
呼字：呼主脾，脾连唇。论云：脾湿即唇焦，有疾作呼，吐纳治之。
嘘字：嘘主肝，肝连目。论云：肝盛即目赤，有疾作嘘，吐纳治之。
吹字：吹主肾，肾连耳。论云：肾虚即耳聋，有疾作吹，吐纳治之。
嘻字：嘻主三焦。有疾作嘻，吐纳治之。
吐纳之义：梁代陶弘景“养性延命录”曰：“纳气有一，吐气有六。纳气一者谓吸也；吐气有六者谓吹、呼、嘻、呵、嘘、(口四)，皆出气也。凡人之息，一呼一吸，元有此数。欲为长息吐气之法：时寒可吹，时温可呼。委屈治病：吹以去风，呼以去热，嘻以去烦，呵以下气，嘘以散滞，(口四)以解极。”
   
* 14
** ...

楼主：星空迷航  时间：2016-07-10 19:46:46
二、修真吐纳六字诀释义
春嘘明目木扶肝：嘘字配属，肝和春，春季吐纳时默读嘘，可以使肝木疏达，眼目明亮。
夏至呵心火自闲：呵字配属，心和夏，夏季吐纳时默读呵，可以使心火收藏，心平气静。
秋(口四)定知金肺润：(口四)字配属，肺和秋，秋季吐纳时默读(口四)，可以使肺气滋润，不为秋燥所伤。
肾吹惟要坎中安：吹字配属，肾和冬，冬季吐纳时默读吹，可使肾阳(肾中火即肾阳，配属八卦之坎卦)收藏，肾气安宁。
三焦嘻却除烦热：嘻字配属三焦，四季吐纳时默读嘻，可使三焦运行无阻，消除烦热。
四季长呼脾化餐：呼字配属，脾和四季，四季吐纳时默读呼，可使脾胃运化功能旺盛，消化、吸收正常。
切记出声闻口耳，其功尤胜宝神丹：行六字诀一定要心中默读，切忌将字读出声，使耳听见。这种练功法诀的作用很好，优胜于服用神丹妙药。
楼主：星空迷航  时间：2016-07-10 20:26:24
三、修真六字诀行功图释义
六字诀行功禁忌：四季常是嘘，八节不得吹。益肝为相火，有泻无补；肾为真水，有补无泻。
行六字诀时可以配合动作，将呼吸默读与肢体运动结合起来进行。
肝若嘘时目睁睛：默读嘘时，要睁大眼睛。
争知肺(口四)手双擎：默读(口四)时，要把双手向上托举。
心呵脑后高叉手：呵时，可将双手举起交叉脑后。
肾若吹时抱膝平：吹时，可将两腿下蹲，用两手抱膝。
脾用呼时须撮口：呼时，要将口唇微收。
三焦客热卧嘻宁：嘻时，要躺卧在床上进行。
禁忌事项：
四季常是嘘，八节不得吹：春夏秋冬四季经常适宜“嘘”字锻炼；立春、春分、立夏、夏至、立秋、秋分、立冬、冬至这八节之时，不得进行“吹”字锻炼。
益肝为相火，有泻无补：肝脏寄藏着能温养全身，推动脏腑功能活动的“相火”，肝性喜条达，宜常疏通宣泄，不宜(手卯)郁填补。
肾为真水，有补为泻：肾主藏精，精又可称为“真水”“元阴”，由父母先天之精和后天饮食之精合成，是人体生长、发育、生殖的本源，宜经常滋补使其充实，不可伐泻使其不足。
楼主：星空迷航  时间：2016-07-10 22:21:48
四、六字诀配五行与主治生克
五行：木、火、土、金、水
五志：怒、喜、思、忧、恐
五脏：肝、心、脾、肺、肾
六字：嘘、呵、呼、口四、吹
五行生克：
相生，就是相互资生和助长；相克，就是相互制约和克制。
相生：木生火，火生土，土生金，金生水，水生木。
相克：木克土，土克水，水克火，火克金，金克木。
我克者，为我所胜；克我者，为我所不胜。
六字诀主治：
肝嘘：主嗌(咽喉)干，面尘(面青无华)，眼眵赤多泪、疼痛，胁下痛，小便黄赤色或涩(小便不利)。
心呵：主烦躁，喉疮热肿，多汗，掌中热，咽干渴。
脾呼：主热痰涏，目黄，喉痹，鼻(血丑)，口干舌痛，身重腹胀。
肺(口四)：主踹(左边口)咳、烦渴、胸膈烦闷，有痰，掌中热，风汗出。
肾吹：主有疾尪(音汪)羸(音类)(尪羸，瘠病、瘦弱)，面黑，口干，耳鸣，咽嗌肿，股内疼痛，足下热痛。
三焦嘻：主颊疼，喉痹，耳闭昏昏然。
以上主治六经本病之邪也。然五脏不足，又在药食气味为补。经云：“形食味”，故味归形；气食形，故形归气。
气化则精生，味和则形长，故五味为宜。若五志所过，非药可治者，五胜为宜。
忧胜怒，肝属木，在志为怒。过节则反自伤，故曰怒伤肝，故以所胜者制之。
恐胜喜，心属火，在志为喜。过节反自伤，故曰喜伤心，故以所胜者制之。
怒胜思，脾属土，在志为思。过节反自伤，故曰思伤脾，故以所胜者制之。
喜胜忧，肺属金，在志为忧。过节反自伤，故曰忧伤肺，故以所胜者制之。
思胜恐，肾属水，在志为恐。过节反自伤，故曰恐伤肾，故以所胜者制之。
各脏的六字诀所胜治疗法：
忧胜怒，肝木有病，可默念“口四”字制约，或“口四”字和“嘘”字交替默念配合治疗。
恐胜喜，心火有病，可默念“吹”字制约，或“吹”和“呵”交替默念配合以治疗。
怒胜思，脾土有病，可默念“嘘”字制约，或“嘘”和“呼”字交替默念配合以治疗。
喜胜忧，肺金有病，可用“呵”字，或“呵”和“口四”交替默念配合以治疗。
思胜恐，肾水有病，可用“呼”，或“呼”和“吹”字交替默念配合以治疗。
楼主：星空迷航  时间：2016-07-10 22:30:44
总结：
六字诀是调理五脏疾病，见效最快效果也良好的一种修行辅助法诀。古代修行人入山后，就依靠六字诀调理五脏疾病。
特别是五志产生的心理病，药难治，但六字诀能调理好。
六字诀与五行是有对应关系的。明白了这个理，则人体的各类疾病皆依之调理。因为人体是由五行构成的。
若精熟先天数理，依之会产生种种变化，效果难以尽数。希望有缘者珍惜之。
楼主：星空迷航  时间：2016-07-16 19:50:18
报道了
楼主：星空迷航  时间：2016-07-23 20:17:33
报道答凝了
楼主：星空迷航  时间：2016-07-23 22:05:44
发过杂说：活化水
做法，把烧开一分钟以上的开水，倒入能密闭的钢瓶中，满，密封。以冷水在外浇注，迅速降温至45～25度间，就成活化水。
活化水，主要是排除了水中的气体，水分子重新排列，能形成大聚合水分子。在密闭降温时，被动的吸收外界灵能，含有较高的序列。
活化水，甘甜，柔和，滑润。进入人体，能直接被细胞利用。有高的溶解性，能把通常不溶的物质溶解。能降低粘性，增强身体活力。
以之浇注植物，开花大花期长，增产增收。种种妙用。
楼主：星空迷航  时间：2016-07-30 19:48:42
星期六到了。
楼主：星空迷航  时间：2016-07-30 19:57:13
今天上午因缘见五音治病有感。准备讲一讲五音在人体修行中的相应关系。
我们修行中，诵的经文，念持的咒语，都是通过声音来传递。那么声音又是怎样把这些信息，转化给人体，产生无量作用的呢？
楼主：星空迷航  时间：2016-07-30 20:11:11
前面讲过，肉体是由五行假合而成。阴阳五行是肉体最本源的法则之一。
那么什么是五音呢？声音、音乐与五行什么关系呢？
我们一步步的来分析。
五音与五行
从本质上说：五音是通过声音频率节奏，调节自然环境与人体(或修行它体)的身体脏腑(肉体)产生共振，传递能量而起到调理身心的功效。 属于音乐治疗疾病调理身心的范畴 。
楼主：星空迷航  时间：2016-07-30 20:22:37
从源流方面讲：
中国古老传统医学有着“五音五行”的说法。《黄帝内经》记载“天有五音，人有五脏；天有六律，人有六腑。”，又载“角为木音通于肝，徵为火音通于心，宫为土音通于脾，羽为水音通于肾。”
所以五音可对相应的五脏起作用，如角音属木，通肝，可制怒，即“通肝解怒”；徵音属火，通心，运用徵音可“养阴助心”；宫音属土，通脾，能解郁舒意；商音属金，通肺，能解忧结行滞；羽音属水，通肾，能消除惊恐带来的不安情绪、打磨志向。
五音又称五声。最古的音阶，仅用五音，即宫、商、角、徵、羽。“五声”一词最早出现于《周礼·春官》：“皆文之以五声，宫商角徵羽。”而“五音”最早见于《孟子·离娄上》：“不以六律，不能正五音。”《灵枢·邪客》中把宫ɡōnɡ、商shānɡ、角jué、徵zhǐ、羽yǔ五音，与五脏相配：脾应宫，其声漫而缓；肺应商，其声促以清；肝应角，其声呼以长；心应徵，其声雄以明；肾应羽，其声沉以细，此为五脏正音。
相传是由中国最早的器“埙”的五种发音而得名。相当于现在的12356，即：do、re、mi、sol、la。 即土，脾，宫 do、1；金，肺，商 re、2；木，肝，角 mi、3；火，心，徵 sol、5；水，肾，羽 la 、 6 。
后来又加上二变，即变宫、变徵，变宫近似现代音乐简谱中的“7”，顺生属金；变微近似现代音乐简谱中的“4”，逆行属木。我国传统的音乐中没有和“4”相当音。五音加二变，合起来叫做“七音”或“七声”，这样就形成了一个七声音阶：宫（1）、商（2）、角（3）、变徵（4）、徵（5）、羽（6）、变宫（7）。 36676656356~~36676656353~~36663323212~~235656321756~~ 171171 32 7765653 17117132 7765666 171171 32 7765653 (有兴趣的可以匹配下这段乐谱中的五行变化，明白了这些变化，能用数字表达的规律就可化为音)。
五行生克前面楼层有说，在音乐中形成的刚柔、阴阳匹配：金为阴（例如阳、柔、刚），水、木为阳（匹配阴、刚、柔），相生、相克能相辅，刚柔结合能协和，刚柔结合，相控相补。
水为阴（阳、柔、刚），木、火为阳（阴、刚、柔)。
木为阴（阳、柔、刚），火、土为阳（阴、刚、柔)。
火为阴（阳、柔、刚），土、金为阳（阴、刚、柔）。
土为阴（阳、柔、刚），金、水为阳（阴、刚、柔）。
楼主：星空迷航  时间：2016-07-30 20:35:44
人体与五音：
术数依五行相生相克之理，将所有的姓氏归于宫商角徵羽五音。辨别五音，倚靠在人体的发音部位：舌为徵，齿为商，牙为角，喉为宫，唇为羽。比如以人的姓氏发音在舌则为徵姓，余类推。
在姓名的音律学中，最复杂的是其五行定义。通过五音在起名中起到病药补益的作用。
我们知道，中国最古老的文化，将世界万物分为“金、木、水、火、土”五行元素，又因阴阳分野，合称“阴阳五行”。五行学说和“阴阳八卦”学说互相参照和补充，共同组成中国古代“玄学”最基础的结构。
传统中医理论，认为土主肌肉，火主血脉，木主筋气，金主骨牙，水主髓液，所以相对于五脏即是土主脾胃，火主心脏，木主肝脏、金主肺腑、水主双肾。
人体五音的配属：
是根据文字的音韵，即其发音；将牙、舌、喉、齿、唇等五音，用木、火、土、金、水等五行为表示的标准。唇音属水性；牙音属木性；舌音属火性；齿音属金性；喉音属土性。
对于口腔来说，稍微复杂一些，首先应明确嘴唇是肌肉组织，故唇一定属五行之土；另外牙齿属五行之金也应当明确。但古人将“牙”和“齿”是分开来讲的，“齿”专指切牙（门齿）和尖牙，“牙”专指双尖牙和磨牙，因此古人对字音有“牙音”和“齿音”的区别。但古人所提到的牙音，并非由臼齿发出的声音，而是指相对来说，经过臼齿的气流较多而已。如果让气流更多的经过臼齿部分，口腔必须要撑开两腮移出部分空间，这要依靠“筋”的力量，故“牙音”属于五行之木；
《内经》称：“心主舌”，又《灵枢 . 脉度》曰：“心气通于舌，心和则能知五味矣”。由于心主火，故此，舌属于五行之火。咽喉在口腔的下后方，喜欢水，最怕干燥，故喉属五行之水。事实上，古人定义的“喉音”包括咽部及上腭等发音位置较置后的声音。分清发音位置而定五行从理论上是最具有说服力的条件，但对于某些字要细细推敲才可以定论。我们也可以在汉语拼音的声母表中大体找到对应。
详见下表：
唇音属五行之土 拼音：b ， p ， m ， f, w
舌音属五行之火 拼音：d ， t ， n ， l
牙音属五行之木 拼音：j ， q ， x ， y
齿音属五行之金 拼音：z ， c ， s ， zh ， ch ， sh ， r
喉音属五行 之水 拼音：g ， k ， h
另：土音：韵母a o e ie ai ei ao ou an en ang eng ong
金音：前摩察音j q x z c s i
木音：舌根音g k h zh ch sh r
火音：舌尖音，d t n l
水音：唇爆音b p m f w
梵文字母的对应，可类此推理。五音分属五行，在中医引导（气功）理论中也有典为证。《正统道藏洞神部》云：“呬字，呬主肺，肺连五脏，受风即鼻塞，有疾作呬吐纳治之。呵字，呵主心，心连舌，心热舌干，有疾作呵吐纳治之。呼字，呼主脾，脾连唇，脾火热即唇焦，有疾作呼吐纳治之。嘘字，嘘主肝，肝连目，论云肝火盛则目赤，有疾作嘘吐纳治之。嘻字，嘻主三焦，有疾作嘻吐纳治之。”以上即前文中的“修真六字诀”，是一种通过吐气发声而强身治病的修身养命之道。
不过，不可以迷信字音的五行信息，与字义字形相比较而言，字音最重要的是谐音内容，即音频节奏。
楼主：星空迷航  时间：2016-07-30 20:39:04
下面推演五行字义与字形，同人体相应：
木木：具有野心，凭努力寻求发展；
木火：品格高洁，但精神方面的劳累多；
土木：富独创力，烦恼亦多，晚年始能成功；
木金：具有为了义理而不顾利害关系的性格，能名扬四海；
木水：踏实而不急躁，为大器晚成的任务；
火火：性急、刚直，容易与人发生摩擦；
火土：温柔敦厚,但缺乏决断力；
火金：执着、稳重，能够成就大师；
火水：几经波折始能成功的运势；
火木：精神方面多烦忧，死后才扬名；
土土：温厚却缺乏决断力，同时也具蛮横无理的个性；
土金：精神充沛，不过表现出来的却是沉默、质朴的个性;
土水：具有勤勉的个性，思虑周密，最后能成功;
土木：具有沉默地努力的个性，因此能建立成功的根基;
土火：个性正直，有招致他人误解之忧;
金金：奋斗心旺盛，也有财运，但家庭运不佳;
金水：有文采，且善辨;
金木：能为他人尽力，声名显赫;
金火：短视近利，思虑不周，因此容易招致失败;
金土：重视承诺，但有容易散财之运;
水水：运势有发展穷向，但稍带阴气;
水木：在技艺上有特除才华，可获至成功;
水火：劳多功少，是困苦重重的运势;
水土：早年因困苦，但中年到晚年时便有成功、幸福之运到来;
水金：早年挫折多，但可凭自力奋斗而开展运势，晚年可过得特别幸福。
上述即为“皇帝内经”中的五行推演而相应的25种人。
根据五气的配合看特殊疾病的方法：
此疾病的看法，是根据名字的头一字之五气，若加上其他的配置不佳时容易出现的疾病。
土性：胃、肠胃病、脾病、花柳病;木性：肝、神经方面的疾病、气喘、胃和肝、胆结石、肺病;金性：肺、晕眩、肿瘤、鼻和齿耳、精神病;火性：心，心脏病、头疼、眼疾、脑病、精神错乱;水性：肾，肾脏病、疝气、子宫病、花柳病、虚冷症。
楼主：星空迷航  时间：2016-07-30 21:12:49
五音与自然人体的对应关系：
天（自然界）有天籁之
五音：角、徵、宫、商、羽，
地（物质）有
五行：木、火、土、金、水，
人有
五脏：肝、心、脾、肺、肾。
五脏所藏：（肝藏）魂、（肺藏）魄、（心藏）神、（肾藏）志、（脾藏）意。
五志：怒、喜、思、忧、恐。
五味：酸、苦、甜、辛、咸。
五色：青、红、黄、白、黑。
宇宙间各种元素（互相联系、转化）相生、相克、相胜、相晦、相对应。所以五脏与五行、五味、五音相对应是音乐治疗疾病的理论基础。
具备万物之灵的人，必然喜欢万物之情的音乐，人和物都与音乐息息相通，音乐可以调和人的性情。
同理，以五色为基本的色彩调理人体与自然环境相应，与此类比。
在诸多乐器中，鼓如同天，埙如同地，磬如同水，这里按五行分为：木（角调式）音、火（徵调式）音、土（宫调式）音、金（商调式）音、水（羽调式）音。
五行养生音乐3-角----肝、胆
木音（角调式音乐）是古箫、竹笛、木鱼等演奏的音乐舒展、悠扬、深远，使人飘逸欲仙；高而不亢，低而不臃，绵绵不断，好似枯木逢春，春意盎然。入肝胆之经，可以疏肝利胆，保肝养目，平和血压、清血质，夜间休息时听有助益安魂人睡，对于疑神疑鬼、精神不安的人，也有很好的理疗效果其它，如夜晚受到惊吓、盗汗、心中忧郁的也相当有益。多听木音，可以转移性情，增强精神，安定魂魄，消除失眠，让身心合一，重新找到原始平和的人性。
木音之意义象征东方苍龙，被认为是能够消灾避祸祛病的吉祥物，象征着强大、健康、向上。鼓舞东方巨龙从大地上缓缓腾空而起，应着角声，朝着太阳，遨游长空。

五行养生音乐5-徵----心、小肠
火（徵调式）音乐　　　火为古琴、小提琴等丝弦音乐，入心经，小肠经，主理心脏和小肠的健康。古琴、古筝弹奏出远古的回音，有轰然绵延的背景音乐，突出古琴的清朗悠扬舒缓的旋律，逐步加快节奏，清脆悦耳的打击乐的叮咚声出现，展现出长河落日的远景。雁过翎翅声、鸣叫声声由远及近，由近而远去，风声水起，云蒸霞蔚，表现出中国远古文化长河优美的回音和片段，令人发思古之幽情。
火是万物的动力，代表心脏，有热量，丝弦的声音可以拨动人的心弦。《黄帝内经》指出：火通心经，疏导小肠经，丝弦音调理神志，，疏导血脉，平稳血压，疏通小肠，祛毒疗伤。聆听火音乐可以使心、小肠处在沉稳和谐的生理状态之中。

五行养生音乐1-宮 土音是宫调式音乐　　是埙、笙、竽、、葫芦笙等乐器演奏的音乐。入胃经、脾经，主理脾胃的健康。
古埙的乐音低沉、缓慢、浑厚仿佛来自遥远的夜空，而小提琴为丝弦乐音，丝为火，火生土，引人进入宁静混沌的宇宙空间。土音是万物化成生成的元音动力，动物植物由单一细胞生化形成，代表新生命的即将诞生，佳音在先，而佳气随后，推动着大自然的变迁和动物植物的生发蜕化.....配合鼓声，鼓声鼓动先天的真气运化，表达各种生物节律与心脏跳动的声音，推动先天真气由单一细胞转化成多元细胞的分化，一分为二，二分为四，四分为八，直至进化到原始人类......考古已经证明，“原始先民吹埙，群民围篝火而听”的传说。所以，伏羲氏“造瑟埙调理百病”的历史传说也是有依据的。

五行养生音乐2-商---肺、大肠
金音（商调式音乐）是金石类材料制造的乐器：如编钟、磬、锣鼓、铃钹、长号、三角铁等演奏的商调式音乐，浑厚、清脆的　金石之声，声声连绵不断地回荡在天地间，气势磅礴、高昂，起伏委婉，震荡心肺，帮助人们扩充肺腑，加大肺活量，吸纳大量氧气，入肺经，大肠经，主理肺、肠的健康。
金石音乐旋律选择了编钟、磬等乐音，能够演奏出中华民族文化气势磅礴的尊贵与威严，宏大嘹亮的编钟音乐显示出了历史鼎盛时期的辉煌，赞颂太平盛世的繁荣昌盛！古典音乐表达了先辈们创造文字、音乐、数学、哲学、医学、历法等高度的文明文化，教化人们心气和平，积善事、调魂魄，行爱心、得神明，从而达到强肺强魄，驱除疾病与后患，增强体质的目的。

五行养生音乐6-羽 水音（羽调式音乐）是鼓、水声等音乐，入肾经与膀胱经，主理7肾脏与膀胱的健康。其旋律模拟地下泉水，溶洞水，山涧小溪、江河、湖泊、海洋的之水声音，风雨雷电交加水，天雷为火，天雨为水，水火相激、济，交响轰鸣，震荡寰宇，天地能量迸发。
水是万物着母，主肾，生命之根，肾气蒸发，天地合，生命诞生。
水声代表生命之源，水声的音乐能够强壮肾脏功能，刺激肾上腺素分泌，疏导下腹，疾患并泄毒，从而平衡免疫系统，提高生命品质。人们敲锣打鼓，乐声喧天，综合了音乐的能量。轩辕鼓、宫廷鼓、手鼓、大小鼓、铃鼓、架子鼓、非洲鼓等十几种鼓声交替震荡，鼓声振奋先天肾脏之气，能量不断延绵，可疏通肾经，促使泌尿系统与性功能发达。水多能够壮肾、旺肝，肝木和谐共鸣，水火济济相融，使人心志通畅，欢乐体壮。
楼主：星空迷航  时间：2016-07-30 21:39:44
五音生克变化与表征：
中医五运六气，提出五音健运，太少相生。五运的十干既各具阴阳，则阳干为太，阴干为少。例如：戊己土宫音，阳土戊为太宫，阴土己为少宫，太为有余，少为不足。
推之：戊为阳土，阳土必生阴金辛，即太宫生少商；阴金必生阳水壬，即少商生太羽；阳水必生阴木乙，即太羽生少角、阴木必生阳火丙，即少角生太徵；阳火必生阴土己，即太徵生少宫。如此太少反复相生，则阴生于阳，阳生于阴，而不断地变化发展。应用五音来表征大自然时空变化的规律，成为“天人合一”学说的重要基石。
1、土乐
凡听宫，如牛鸣窌中，音调缓慢而悠长，若是诵念经文，会充满规劝人的力量，佛门高僧吟唱，一般都是走宫音。
以宫调为基本，风格悠扬沉静、淳厚庄重，给人有如“土”般宽厚结实的感觉，根据五音通五脏的理论，宫音入脾，对中医脾胃功能系统的作用比较明显。
2、金乐
凡听商，如雄鸡打鸣，商音的力量，十分的短促和清越，爆发力极强。
以商调为基本，风格高亢悲壮、铿锵雄伟，肃劲嘹亮，具有“金”之特性，根据五音通五脏的理论，商音入肺，对中医肺功能系统的作用比较明显。
3、水乐
凡听羽， 如负猪豕觉而骇 ，声音比较低沉而尖细，穿透力十分的强。
以羽调为基本，风格清纯，凄切哀怨，苍凉柔润，如天垂晶幕，行云流水，具有“水”之特性，羽音入肾，对中医肾功能系统的作用比较明显。
4、木乐
凡听角，如雉登木以鸣，音疾以清，舒缓清晰，声音中充满了生机，适合用来养生。
以角调为基本，风格悠扬，生机勃勃，生机盎然的旋律，曲调亲切爽朗，舒畅调达，具有“木”之特性，角音入肝，对中医肝功能系统的作用比较明显。
5、火乐
凡听徵， 如鸣马在野 ，徵声听起来十分的雄壮高亢，充满了震慑威严的力量，适合用于吼声之中，声音一出，让你胆气先失。
以徵调为基本，旋律热烈欢快、活泼轻松，构成层次分明、情绪欢畅的感染气氛，具有“火”之特性，徵音入心，对中医心功能系统的作用比较明显。
楼主：星空迷航  时间：2016-07-30 21:47:48
音乐与调理：
中医认为七情过激引起气机的过度变化，“怒则气上，恐则气下，惊则气乱，喜则气缓，忧则气聚，悲则气消，思则结。”情绪过激能导致体内功能失衡，是引起情志因素疾病的主要因素。
《素问·阴阳应象大论》说：“怒伤肝，悲胜怒；喜伤心，恐胜喜；思伤脾，怒胜思；忧伤肺，喜胜忧；恐伤肾，思胜恐。” 当某种情绪过甚而致发病时，可以用另一种“相胜”的情志来“转移”、“制约”或“平衡”它，从而使过度的情绪得以调和。
健脾：1(哆)；强肺：2(唻)；强肾：46(发啦)；舒肝：73(西咪)；强心：5(索)。
举例，肝阳上亢类型高血压病人，容易发怒，我们给予有商调式或悲伤色彩较浓的音乐聆听，如《小胡笳》、《江河水》、《汉宫秋月》、《双声恨》和《病中吟》等，这些乐曲，以悲情见长，凄切感人，有良好制约愤怒和稳定血压作用，比较其它类型音乐差异显著。
如果是阴虚阳亢类型患者，还可以选择羽调的水乐，如《二泉映月》、《寒江残雪》、《平沙落雁》、《潇湘水云》、《小河淌水》等，这些乐曲有柔和、清润的特点，能导引精气，滋阴潜阳。
有时候，根据具体心理特点，投其所好，安排一些有欢乐愉快类型的乐曲，如《花好月圆》、《喜洋洋》《瑶族舞曲》《喜相逢》《鸟投林》等，或升发调畅类型的音乐，如《光明行》、《霸王卸甲》《战台风》《赛龙夺锦》等，使患者进入情绪状态，或温厚、中和类型的音乐，如《梅花三弄》《阳春白雪》《霓裳曲》《满庭芳》《忆多娇》等，使得患者的愤怒情绪需要顺势转移、宣泄或抚慰，再以悲调乐曲施之，则亢阳兴奋的状态得到化解，气血回复平衡，心中平和自然显现。
下面对照举例：
五行归相 ：调式阴阳：曲目：意境： 功效 ：适用症
脾属土，在音为宫，在志思 :
① 阳韵/ 黄庭骄阳 /骄阳似火湿气尽消 /温中健脾升阳益气 /食少腹胀，神疲忧郁。腹泻、脏器下垂等。
② 阴韵 / 玉液还丹 /清泉润泽清凉甘甜 /清火和胃清积导赤 /胃脘胀痛，内火郁积。
肺属金，在音为商，在志为忧: ① 阳韵 / 晚霞钟鼓 /晚霞满天钟鼓振荡 /补益肺气宽胸固表/ 喘咳无力，自汗怕风。
② 阴韵 / 秋风清露 /秋月清朗清露寒爽 /滋阴清热润肺生津/ 干咳少痰，身心烦热。
肝属木，在音为角，在志为怒: ① 阳韵 / 玄天暖风 /春风和暖阳光明媚万物葱荣 /补益肝气散寒解郁 /眩晕耳鸣，夜寐多梦，肢体麻木
② 阴韵 / 碧叶烟云 /春风清寒绿叶青翠 /清肝泻火平肝潜阳/ 头晕胀痛，烦躁易怒，面红目赤，失眠多梦。
心属火，在音为徵，在志为喜:
① 阳韵 / 荷花映日 /夏日炎炎荷花清香四溢 /补益心阳养心安神 /心悸不安，胸闷气短，失眠多梦。
② 阴韵/ 雨后彩虹 /雨后爽洁彩虹明丽 /清心降火安神定志/ 心胸烦热，面红口渴。
肾属水，在音为羽，在志为恐: ① 阳韵 / 伏阳朗照/ 冬日正午阳光温暖寒中见暖 /温补肾阳固精益气 /腰膝酸软，畏寒肢冷。滑精阳痿，宫寒带下。
② 阴韵 / 冰雪寒天/ 冰雪清寒天地纯净 /清心降火滋肾定志 /心烦意乱，眩晕耳鸣，梦遗闭经。
楼主：星空迷航  时间：2016-07-30 22:00:50
还能加楼吗？
楼主：星空迷航  时间：2016-08-06 19:41:11
哎，飞一般的又到了周六，就像昨天
楼主：星空迷航  时间：2016-08-06 19:48:48
因为有修行的问我什么是静坐，今天就答她提示给大家：
心不外驰。心神内收缩为一，就是最好的静坐。
姿势，初单盘即可，女收缩右足贴于会阴部，左足随意在外，自然为度。男则左足贴于会阴，右足随意在外。
双盘，是使脊椎正直，让人精神集中，不容易瞌睡；也使中脉拉伸，易于同天地沟通，打开脉轮；双盘时眼观鼻，垂于心，容易排除杂念，入静。
双盘之后，起身前，要先散盘，以手揉膝关节，拍拍腿，活动血脉；再伸展双腿，舒展几下后，始可起身，进入正常状态
楼主：星空迷航  时间：2016-08-06 21:23:51
今天讲讲河洛。下次讲进化基础
* 15
** ...

楼主：星空迷航  时间：2016-08-06 21:32:16
河图(在这里谢谢天涯的爱护，也能发图了)：


上图，左面8实心3圈，上面7个圈2实心，右面9圈4实心，下面6实心1圈，中间10实心5圈。
实心，代表阴、阴数；圈，代表阳、阳数。
楼主：星空迷航  时间：2016-08-06 21:45:44
河图，传说古时有龙马，从河水(黄河)出来，其背上的毛色，长有很多的黑白圆点，古人将其描画下来，就是今天上面的河图。
这是银河系运转，在地球上产生的共振全息图。
同当年的哈雷彗星蛋一样。在每年的哈雷彗星临近地球时，必然在地球上会出现一个哈雷彗星蛋。即某一动物下的蛋的外表，出现了哈雷彗星的图案。(这个，大家自己去百度，找资料太麻烦了)
先秦之后，始皇帝焚书坑儒，河图洛书也就进入密传，直到宋朝陈传老祖，才将河图洛书传承公开，为众所知。
楼主：星空迷航  时间：2016-08-06 22:18:31
我们先将方位化入，即左面，东方，阴数8阳数3；上面，南方，阳数7阴数2；右面，西方，阳数9阴数4；下面，北方，阳数1阴数6；中央，阴数10阳数5。
古人有云：天一生水，地六成之；地二生火，天七化之；天三生木，地八育之；地四生金，天九润之；天五生土，地十合之。
所以，东方甲乙为木，为青龙，在数为38，甲为阳木，配数3，乙为阴木，配数8；
南方丙丁火，为朱雀，在数为27，丙为阳火，配数7，丁为阴火，配数2；
西方庚辛金，为白虎，在数为49，庚为阳金，配数9，辛为阴金，配数4；
北方壬癸水，为玄武，在数为16，壬为阳水，配数1，癸为阴水，配数6；
中央戊己土，为麒麟，在数为510，戊为阳土，配数5，己为阴土，配数10。
此为先天生成数之由来。十个天干，甲乙丙丁戊己庚辛壬癸，也就是古人用来，表示河图生成变化规律的。
这也是先天五行变化数理。
楼主：星空迷航  时间：2016-08-06 22:39:13
河图中，阳数，1、3、7、9，顺行；阴数8、6、4、2逆行。
故天之阳气顺时针旋转，天之阴气逆时针旋转，合而成太极。这是先天图。
在来看看洛书：

上面图，右面的就是洛书。图中圆点的阴阳含义与前面一样。
我们把方位带入洛书，则有：东方，震卦，在数为3；东南，巽卦，在数为4；南方，离卦，在数为9；西南，坤卦，在数为2；西方，兑卦，在数为7；西北，乾卦，在数为6；北方，坎卦，在数为1；中央，为游宫，在数为5。
楼主：星空迷航  时间：2016-08-06 22:55:42
洛书，传说远古时有圣王伏羲氏，欲把天地的规律，化生出来以教化百姓，他近取诸身，远取诸物，怎么也差一点，不能成功。
一天，来到了落水(洛阳附近)，在观与洛水相通的玉池时，从池爬出一只白龟，龟的背上有许多黑色的线条，他把这些线条画下来，就是八卦图。


楼主：星空迷航  时间：2016-08-06 23:11:57
我们知道，八卦图有先天八卦图和后天八卦图，那么洛水出的八卦图是先天还是后天呢。
洛水伏羲氏成功的八卦图，是白龟共轭地球的全息图，是后天八卦图！
所以，在这里看帖人一定要明白源流，八卦图是先有后天。
先天八卦图，是先贤研究河图和后天八卦图时反推出来的。这里面隐藏着更为高等的奥秘，现在不是时候不讲。
洛书的后天八卦，同哈雷彗星蛋一个道理。同前面的龙马也一个道理。就是天地全息共振规律。
楼主：星空迷航  时间：2016-08-06 23:22:10
那么河图洛书有什么关系呢？河图代表星系的运转规则，洛书代表大地的运转规则。
太阳，是银河系中的一颗恒星。地球，是太阳系中的一颗行星。所以，河洛也是可以相互转化的。
楼主：星空迷航  时间：2016-08-06 23:51:30
图(已经裁剪为二)：


楼主：星空迷航  时间：2016-08-06 23:52:00
图二：


楼主：星空迷航  时间：2016-08-07 00:00:02
看了上面的内容，应该明白河洛之变化了。那么河图中隐藏的也揭示一二。
河图中的阴数和阳数的旋转，与人体的DNA螺旋是一个道理。今后会讲道这个问题。
河图中的5和10就代表了宇宙隐藏的那些。
河洛的其他生化，就留给大家悟吧，在这里说透了也就没人珍惜先贤了。
楼主：星空迷航  时间：2016-08-07 00:20:02
看帖的朋友们，有紧急情况的，加百度贴吧的指引异动为好友，说明是天涯来的某某。
有隐私唤我，可以自动随时提醒我。在这个帖子里我回复了，有紧急情况的也可能没来看了。又没有自动提醒的。
楼主：星空迷航  时间：2016-08-13 19:55:45
周六到了。时间过得真快啊
楼主：星空迷航  时间：2016-08-13 20:11:14
进化内容：手机容量不足，许多图片发不上。等电脑修好后，再说。
请大家待时。
楼主：星空迷航  时间：2016-08-13 20:26:13
这段时间，天机慢慢显示了。大气中的煞气已达到接近一层了。
地球上的生灵，都会无明的暴怒。心中会无缘无故的出现残暴之意，想粉碎看见的或刺激的某种物体，就是受大气中的煞力影响。
修行的，不仅要克制消除自己心中出现的残暴之念，也要尽量调理亲友们心中的暴意带来的矛盾。顺着他们的想法，加以分析，缓和或消除矛盾。注意心灵的疏通。
不注意，往往很多小事，受煞气影响，就会争论成大事件。
因煞气而暴力，今后，将会愈来愈多。或许，劫难近了。
楼主：星空迷航  时间：2016-08-13 21:44:25
朋友们，可以存一些食盐了。现在还应该能买到真的加碘盐，存放也不会变质。
楼主：星空迷航  时间：2016-08-20 20:20:53
进化初论，暂缓，时机依然不成熟。今天我会把家族传承的事件，讲给大家。
因为，除了我之外，他们都不在意了。很多东西，会慢慢遗忘。
楼主：星空迷航  时间：2016-08-20 21:21:14
我家族传承的第二件事：地下鸡叫。
传说，在古时，家族居南地，缺少洁净饮水。有兄弟二人，专事打井，第一口井，打了一年半，没水。
换打第二口井，打了快三年，没见水。从上面下到井底，在回归都要三天时间。
突然一天，他们在井下，听见了，从地底下方传来了鸡叫的声音。惊动了全族，经过族里考证，每天都会有鸡叫声，传出。最后，族里封闭了此井，并将这件事作为传承，一代代到如今。
打井，这件事，当时不少堂兄们都上过现代初中了。同父辈爷爷们争论很凶，对我应像最深刻的是两个数据，其一是，爷传孙，一辈是按20年记还是40年算，按40年仅仅传承就超过华夏文明5000年了，所以是假的(被大爷爷们用烟杆头敲脑袋，看见大兄们长辈手蒙着头辩论)。按20年，才2000多年，与来源上古又不合。
其二是，打井听见鸡叫到现在，有80多代。
楼主：星空迷航  时间：2016-08-20 22:02:10
第三件事是：洪水登天。
传说远古时，先辈们在南方开疆守土，一天，一个白发子老人送给了两粒葫芦种子，让他们赶快种下，后有大灾难，可以入葫芦躲灾。
先辈们种下后，浇上水，见风就长，三个月就像高楼了，半年后就长得像小山一样高大。
先辈们，就把吃得用的养的，把家搬入了葫芦里面。把葫芦用长长的铁链锁在了高山上。
不久，黑风暴雨来了。连续下了六十几天的大暴雨，一切都被洪水淹没，高山成了小岛。
雨停后，天晴了，他们打开了葫芦，高山周围一片汪洋。
又过了(一说一个半月；一说三个月)，洪水消了，很多大地露出了。但原来低洼的田地都成了水域湖泊，人们被逼在山林中生活。
为了后代不忘这些大事，家族的传承，就是从这时开始设立。所有大地上逃生的族群，都被建立了传承，受命将这些大事一代代传下去。
楼主：星空迷航  时间：2016-08-20 23:02:58
家族传承的杂事：
其一，成都平原的来历。传说洪水登天后，整个天府之国都成了一个大海子。
后来人们挫穿了三峡，放了近百年，才将四川盆地的大量的水放掉，露出大地来。
但成都平原依然是一个小海子，人们又挫穿出岷江，排了20多年的水，成都平原才露出大地。
观音菩萨又用一炉香灰，倒在了成都平原的大地上，让大地变成了平原良田。
其二，汉中平原来历。
治水的后期，西边多山，东边的平原多涝。有高人受命，用赶山鞭，把秦岭一带的山头，赶往东海。
高人用赶山鞭把山头，化为兽群，赶向东方。当赶出八百里汉中平原后，他准备休息一下在继续。
其一，赶山鞭只能夜晚才能变化山头，他睡着了，等他鸡叫醒来，兽群已复原为山头，不能赶了。
其二，他休息时，一个童子在观看赶山鞭，突然尿胀了，淋了赶山鞭，破了赶山鞭的法能，等他醒来就赶不了山了。
所以，汉中平原只得八百里(古)。
第三，修造的黑线。
传说，古时治水，人们打造出了很多功能强大的法器。
修筑开山的墨斗就是其中之一。这墨斗，能从中拉出一根很长的魔线，只要用水把魔线打湿，在把魔线的两端固定在山头，用手一弹魔线，就能裂山开石。
一位高人(？)受命，用墨斗去建宫殿，他带着三个徒弟。一天，轮着三徒弟去打水了。
三徒弟拿着墨斗，看了看四处的山石，打水得到几十里外的山下，他偷懒，就淋了一泡尿在墨斗里。
师傅拿着墨斗，就再也没了裂石开山的法能了。从此后，匠人们就只好，发明了用锯子、钢芊、大锤来做修造了。
墨斗的魔线，也只能用墨汁清泡，变成了只能用来划线的墨线。
楼主：星空迷航  时间：2016-08-28 08:57:58
手机故障(阅览器更新什么的)，导致周六登不上天涯，对等待的朋友们说一声对不起。
   
* 16  
* 17
* 18
* 19
* 20
* 21
* 22
* 23
* 24
* 25
* 26
* 27
* 28
* 29
* 30
* 31
